### ISSUE TITLE
[terra-tabs] Enhancement - Appearance of dropdown content in Fusion theme

### ISSUE THREAD

**Issue by jeremyfuksa** [cerner/terra-framework#1001]
# Feature Request

When in MPages tiny viewport, dropdown content should span the width of the dropdown component in order to be visually consistent with components developed in Fusion.

## Description
Tabs rendered in tiny viewport currently show dropdown content in a 50%, right-aligned box. It needs to be 100% in the Fusion theme.

## Additional Context / Screenshots
From the PowerChart team:
<img width="1093" alt="Unknown" src="https://user-images.githubusercontent.com/726351/72269652-931c9f00-35e9-11ea-97ce-f29009e76c36.png">

**Comment by avinashg1994** [comment]
As per my investigation, there is no theme variable as of now which can be used to set the width of the dropdown menu. Any changes to resolve this would affect the default behaviour.
Terra-Tabs internally uses terra-menu to implement the collapsed tabs, which defaults to 240px as seen [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-menu/src/Menu.jsx#L61) because there is no value being passed down from terra-tabs : [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-tabs/src/_TabMenu.jsx#L125-L131)
Since this behaviour persists in default theme as well, my suggestion would be to fix the default behaviour.
@neilpfeiffer, @jeremyfuksa your thoughts on this?

**Comment by jeremyfuksa** [comment]
My thought is, yes, we should fix the default behavior for that viewport across all themes. Looking at Zeplin, I see that visual guidance was given for how to handle tab dropdowns for larger viewports, and my assumption is that a completely responsive solution just didn't get coded.

However, this particular issue could use a little extra input from the UX Foundations team since we're talking about design changes that aren't explicitly called out. Let me pass this issue on to another set of eyes before we begin this change.

**Comment by jeremyfuksa** [comment]
Based on the discussion I just had, this is OK.

This component is one that will likely get a UX Foundations enhancement in the future, so theme variables would be good. But the open-source theme doesn't need to follow Fusion's treatment at that viewpoint. We'll handle open-source behavior (as well as overall interactivity) with the enhancement project.

**Comment by jeremyfuksa** [comment]
Closing because this would be addressed in an open source enhancement to terra-tabs.
