### ISSUE TITLE
[terra-date-time-picker] Error occurs on focus during a remount

### ISSUE THREAD

**Issue by eamavizca** [cerner/terra-framework#1086]
# Bug Report

## Description
There is currently no first-class support for programmatically setting the value of a DateTimePicker. The common workaround of setting a key prop to force a re-mount breaks the blur/focus functionality to switch the user between fields and introduces a console error.

## @ Mentions
@benbcai

**Comment by benbcai** [comment]
Due to the fact that date-time-picker currently can only be used as an uncontrolled component, its `value` prop behaves like a `defaultValue` prop where it is used only as the default value in the initial render. To make this passive, we would need to introduce a new prop (e.g. `controlledValue`) that can be used by consumers to update the date/time value. Either only the `value` or the new `controlledValue` prop should be used during the entire life cycle of the component. Both cannot be used together.
 
The main changes include:
- Whenever the new `controlledValue` prop is used, the internal state (`this.state.dateTime`) and variables (`this.dateValue` and `this.TimeValue`) must be updated, potentially in getDerivedStateFromProps, every time this prop changes. It would be the consumer’s responsibility to manage this value by handling the onChange and onChangeRaw callbacks.
- Every time the new `controlledValue` prop is changed, it is required to check if the updated value is ambiguous. If it is ambiguous, we need functional feedback on when the ambiguous dialog should be displayed. Would it be too disruptive to display it immediately in componentDidUpdate? Should it wait and be displayed if and when focus is lost? What happens if the component does not gain focus again?
- Some tweaks are needed to ensure that the date and the time remain synchronized if using the `controlledValue` prop.

**Comment by eamavizca** [comment]
In our case, we are in an errored state where the user attempted to save modifications to a form but there was a stale data error. We present them with an option to refresh the form with the currently saved data:

![image](https://user-images.githubusercontent.com/52928047/78577484-bffcde80-77f3-11ea-9dc7-22171d5d468a.png)


When updating the controlled value, we would expect it to display the same as if it was the initial value passed in - no ambiguous dialog because it's loading a saved value.

To clarify on the console error received when using the key workaround - this is what's thrown:
![image](https://user-images.githubusercontent.com/52928047/78577934-6e088880-77f4-11ea-9525-17ef77dce9ca.png)

This is likely caused because "this" no longer exists after forcing a re-mount of the component. The side-effect of this error is that the time field is not automatically focused after selecting a date.

**Comment by eamavizca** [comment]
> Whenever the new controlledValue prop is used, the internal state (this.state.dateTime) and variables (this.dateValue and this.TimeValue) must be updated, potentially in getDerivedStateFromProps, every time this prop changes. It would be the consumer’s responsibility to manage this value by handling the onChange and onChangeRaw callbacks.

Is there a reason this can't be simplified for consumers to have a single callback that returns the ISO-8601 of the combined date + time fields?

**Comment by benbcai** [comment]
> This is likely caused because "this" no longer exists after forcing a re-mount of the component. The side-effect of this error is that the time field is not automatically focused after selecting a date.

Yes, this error is coming from [here](https://github.com/cerner/terra-framework/blob/24442b16156b47652d39b951f9b975cdb73409f2/packages/terra-date-time-picker/src/DateTimePicker.jsx#L377) where it no longer has the reference to `hourInput` after the timeout due to the remount.

**Comment by benbcai** [comment]
After reviewing this with the Terra team, it was decided that we will fix the above error/bug that is caused when a remount occurs. A new enhancement issue will be logged to investigate how best to address the original request to allow updating the date/time value.
