### ISSUE TITLE
Faceup Date Picker

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-framework#1098]
# Feature Request

## Description
Create a face-up date picker to allow quick day selection. A face-up calendar would be useful in a Scheduling application. This picker should have the same behaviors as the current date picker except the calendar will always be displayed face-up and without the input.

## Additional Context / Screenshots
![Screen Shot 2020-04-27 at 8 39 31 AM](https://user-images.githubusercontent.com/22618655/80378728-b4d12780-8862-11ea-953f-6eb049573d01.png)

**Comment by benbcai** [comment]
## Tech Design

### Changes

- Add a new first-class boolean prop named `inline` in DatePicker and DatePickerField. This prop should be passed to [react-datepicker](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/react-datepicker/index.jsx#L150) to render an inline version of the calendar. When `inline` is set, the current logic will not render the date input and calendar button. Only the Calendar will be rendered.
- When inline add border style to the calendar container.
- When `inline` is set, ensure that the [withPortal](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L430) prop is always false to prevent displaying the portal version of the picker in small breakpoints.
- When the default date is excluded, filtered, or outside the min/max range, the default date should not be set in the calendar as the selected day. The current behavior is that the default date will be set in the input but as soon as focus is set on the input or when the picker opens, the default date gets cleared. See this [example](https://engineering.cerner.com/terra-framework/tests/terra-date-picker/date-picker/date-picker-default-date-excluded).
- Update the description for the following props to note that they are ignored when `inline` is set.
  - `disabled` - See note below.
  - `inputAttributes`
  - `isIncomplete` 
  - `isInvalid` - See note below.
  - `name` 
  - `onClickOutside` 
  - `required` 

### Investigations
- The `onFocus` and `onBlur` props are currently applied in the date input. When inline these props should be applied to the calendar container.
- When inline the focus cannot be set on the calendar days. This might be due to this [line](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/react-datepicker/day.jsx#L109) checking for the `inline` prop.
- There should not be a focus border on the selected day as in the popup picker.
![Screen Shot 2020-04-27 at 9 03 35 AM](https://user-images.githubusercontent.com/22618655/80381168-26f73b80-8866-11ea-8103-639aa68a4929.png)


### Decisions To Make
- The current `disabled` prop makes the date input disabled. When inline should the `disabled` prop be applied to the calendar container to prevent interaction.
- The current `isInvalid` prop add a red border the date input to denote the value is invalid. When inline should the `isInvalid` prop set a red border on the calendar container.
- When the `minDate`/`maxDate` or `includeDates` props are set that potentially hides the Previous/Next month buttons, the width of the calendar is narrowed to eliminate the extra white. This will become more noticeable in the face-up calendar. In this scenario should the Previous/Next month buttons be disabled instead of hidden to keep the width consistent?
![Screen Shot 2020-04-27 at 9 09 27 AM](https://user-images.githubusercontent.com/22618655/80382118-81dd6280-8867-11ea-8024-f3253820161d.png)

**Comment by ShettyAkarsh** [comment]
Hi @benbcai, i am just curious here like are you saying this FaceUp Datepicker should always be rendered by calling the new inline prop of the Datepicker ? if yes, then why shouldn't we keep this subcomponent as separate like allowing Consumers to consume directly the InlineDatepicker instead of tightly coupling this with existing Datepicker ?

**Comment by supreethmr** [comment]
## React Props For Inline Date-Picker :

| Prop | Type | Default | Description |
|----------|------|---------|--------------|
| excludeDates | Array of String | undefined |  An array of ISO 8601 string representation of the dates to disable in the picker. The values must be in the `YYYY-MM-DD` format |
| filterDate | function | | A function that gets called for each date in the picker to evaluate which date should be disabled. A return value of true will be enabled and false will be disabled. |
| includeDates | Array of String | undefined | An array of ISO 8601 string representation of the dates to enable in the picker. All Other dates will be disabled. The values must be in the `YYYY-MM-DD` format. |
| maxDate | string | undefined |  An ISO 8601 string representation of the maximum date that can be selected. The value must be in the `YYYY-MM-DD` format. |
| minDate | string | undefined |  An ISO 8601 string representation of the minimum date that can be selected. The value must be in the `YYYY-MM-DD` format. |
| onBlur | function | undefined | A callback function triggered when the date picker component loses focus. This event does not get triggered when the focus is moved from the date input to the calendar button since the focus is still within the main date picker component. The first parameter is the event. The second parameter is the metadata to describe the current state of the input value at the time when the onBlur callback is triggered. |
| onChange | function | undefined | A callback function to execute when a valid date is selected or entered. The first parameter is the event. The second parameter is the changed date value. The third parameter is the metadata to describe the current state of the input value at the time when the onChange callback is triggered. |
| onFocus | function | undefined | A callback function triggered when the date picker component receives focus. This event does not get triggered when the focus is moved from the date input to the calendar button since the focus is still within the main date picker component. |
| onSelect | function | undefined | A callback function to execute when a date is selected from within the picker. |
| required | boolean | false | Whether or not the date is required. |
| selectedDate | string | undefined| An ISO 8601 string representation of the default value to show in the date input. The value must be in the `YYYY-MM-DD` format. |
| value | string | none | The date value. This prop should only be used for a controlled date picker. |

## Example:
```javascript
import InlineDatePicker from 'terra-date-picker/lib/InlineDatePicker';

const DatePickerDefault = () => (
  <div className={cx('content-wrapper')}>
    <InlineDatePicker />
  </div>
);

export default DatePickerDefault;
```

**Comment by benbcai** [comment]
@ShettyAkarsh Although the face-up calendar can be derived from using the `inline` prop, we want to continue to leverage most of the existing logic in Datepicker. The only reason I prepared a subcomponent instead of a separate new component is that there won't be much implementations for this new component. It will essentially be a wrapper of the DatePicker with a with the addition of the `inline` prop and the removal of the props mentioned above. So there won't be much content for a new component since most if not all of the implementation details would still be in DatePicker. I'm open to hear other people's thoughts.

**Comment by benbcai** [comment]
@supreethmr We shouldn't need the `required` prop since this is not a form field. After thinking about this a little more I also don't think we need `onChange` either also because this is not a form field. We already have `onSelect` which serves as `onChange`.

**Comment by ShettyAkarsh** [comment]
@benbcai , I agree that most of this new component implementation details will be used from Datepicker. but in terms of future maintainance effort for the InlineDatepicker component i was thinking that it would be better to have the InlineDatepicker component as separate component and create the reusable files to share the common logics between this new and Datepicker component. instead of using the entire DatePicker component inside this subcomponent.

**Comment by supreethmr** [comment]
Thank you @benbcai for your inputs, I have removed `onChange` and `required` prop from inline-date-picker and updated the same in above props table.

**Comment by supreethmr** [comment]
> Suggestions for the subcomponent name: InlineDatePicker, CalendarPicker. Open for suggestions.

Since it appears more as an `Calendar` than date-picker I think  'CalendarPicker` Component name would suit to both purpose and appearance of component.

**Comment by supreethmr** [comment]
> @ShettyAkarsh Although the face-up calendar can be derived from using the `inline` prop, we want to continue to leverage most of the existing logic in Datepicker. The only reason I prepared a subcomponent instead of a separate new component is that there won't be much implementations for this new component. It will essentially be a wrapper of the DatePicker with a with the addition of the `inline` prop and the removal of the props mentioned above. So there won't be much content for a new component since most if not all of the implementation details would still be in DatePicker. I'm open to hear other people's thoughts.

I agree with @benbcai  Face-up Date-picker would have no specific implementation / unique functionalities with current requirement. From design it looks more similar to date-picker-field sub-component which just has `<field>` wrapper around date-picker and has less / no specific implementation within it. 

Face-up date-picker also has no specific implementation or functionalities that are unique from date-picker Except passing `inline` prop to date-picker. So IMO I don't think with current requirements face-up date-picker would not suit to be a separate component.

**Comment by benbcai** [comment]
> > Suggestions for the subcomponent name: InlineDatePicker, CalendarPicker. Open for suggestions.
> 
> Since it appears more as an `Calendar` than date-picker I think 'CalendarPicker` Component name would suit to both purpose and appearance of component.

Another name the Terra team came up with is `Calendar` but this name is also very generic and we may want a more specific name. So it was suggested that we need to have UX weight in on the name.

cc/ @jeremyfuksa @neilpfeiffer 

So far the suggestions are:
- `InlineDatePicker`
- `CalendarPicker`
- `Calendar`

**Comment by benbcai** [comment]
> 1. while working on inline-date-picker I found that we are not passing `name` prop in inline-date-picker to date-picker due to this it throws Required prop validation Error. So do we need to add name prop here as well...? Since it should be unique Either we need to make it as read it from prop  in inline-date-picker OR else we might need to generate random name for inline-date-picker.

The `name` prop has no implication for the face-up calendar since there is no input field so we could just hard-code it component name (whether it be "terra-inline-date-picker", "terra-calendar-picker", etc). 


> 2. Navigation buttons (Next Month and Previous Month) seems to larger in Tiny and Small viewports as shown in below image .
> 
> <img alt="Screen Shot 2020-05-12 at 6 56 45 PM" width="230" src="https://user-images.githubusercontent.com/12869809/81702182-9422e780-9488-11ea-9d74-6742c5ab4e32.png">
> 
> This happens even in existing Date-Picker as well. So would like to know is this Intentional presentation of buttons on smaller viewport OR do we need to keep it same across all the view-ports.

That's a good catch. The difference in the Previous/Next month button size was added on [PR #866](https://github.com/cerner/terra-framework/pull/866/files#diff-51e1bb4a0aafbfca4d959f9018880c8aR481-R487) to adjust the size based on whether it is in the [portal](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L430) or popup mode. We would want to keep the flexing of the button size between portal and non-portal like how it behaves. However, since the face-up calendar will be fixed in size (at least for now), we would want the size of the Previous/Next month buttons to also be fixed but only for the face-up calendar.

**Comment by neilpfeiffer** [comment]
### Component Name:
Since the justification for using the `inline` prop naming being derived only from how the originating react-datepicker has exposed this type of ui -- that detail is mostly unknown and hidden to our consumers -- so lets not call it inline, since it will have confusion with other Terra form components where when we make them inline, we change from block style to inline-block and fit more on a single row, which is not the case here.

Let's name it this "Calendar Date Filter" since we aren't actually using this to pick a day to return to submit to a form, but rather is intended to be an interactive filter that changes some alternate dependent UI item, which will be a full page scheduling month/day view. 

So usage would be like this:

```javascript
import CalendarDateFilter from 'terra-date-picker/lib/CalendarDateFilter';

```

**Comment by neilpfeiffer** [comment]
Not sure if this was previously mentioned as a detail, but this filter/picker must always have a selected date and could never be blank (like the normal date-picker can). So unless a selected-date is already provided, then either the current date is assigned as the selected date, or nearest available date if the current date is out of range / excluded as an available date option.

**Comment by benbcai** [comment]
> ### Component Name:
> Since the justification for using the `inline` prop naming being derived only from how the originating react-datepicker has exposed this type of ui -- that detail is mostly unknown and hidden to our consumers -- so lets not call it inline, since it will have confusion with other Terra form components where when we make them inline, we change from block style to inline-block and fit more on a single row, which is not the case here.
> 
> Let's name it this "Calendar Date Filter" since we aren't actually using this to pick a day to return to submit to a form, but rather is intended to be an interactive filter that changes some alternate dependent UI item, which for the immediate requesting consumer will be a full page scheduling month/day view.
> 
> So usage would be like this:
> 
> ```js
> import CalendarDateFilter from 'terra-date-picker/lib/CalendarDateFilter';
> ```
> 
> We will need to have decent examples on the documentation page showing why this component is different than a form element and what its' intended use is for as a companion to additional UI.
> 
> If Filter is not as strong of a name for everyone, these names are acceptable alternatives still using Picker:
> 
> * `CalendarDayPicker`,
> * `CalendarDatePicker`, or
> * `CalendarPicker`
> * ... or could shorten to `CalendarFilter`

As Neil mentioned earlier that this is used to "filter" dates as opposed to "pick" a date so I actually like having `Filter` in the name because it shows a clear distinction between this calendar and the existing date picker. I vote for `CalendarFilter` followed by `CalendarDateFilter` just because having "Date" together with "Calendar" sounds a little redundant...but I'm happy with either one.

**Comment by supreethmr** [comment]
> some logic that determines the nearest available date if the current date is out of range / excluded as an available option.

I am bit confused in determining nearest available date when current date is out of range / excluded. It's difficult to identify the nearest available date when we have series of date excluded or out of range including current date.

> Not sure if this was previously mentioned as a detail, but this filter/picker must always have a selected date and could never be "blank" or unselected value (like the normal date-picker can).

I think we might need to have it as blank when current date is not available.  

need suggestions to proceed with further implementation.

**Comment by neilpfeiffer** [comment]
Ahh yes. Without infinitely testing other date combinations, this will not be possible. 
We instead should plan handle with an example and instructions in the case where consumers provide excludeDates, filterDate, minDate, or maxDate, we recommend to also calculate a selectedDate that they know would be within their range.

Leaving as blank will be the only knowable option from the component's perspective.

**Comment by supreethmr** [comment]
> We instead should plan handle with an example and instructions in the case where consumers provide excludeDates, filterDate, minDate, or maxDate, we recommend to also calculate a selectedDate that they know would be within their range.

Yes, I will add an example with instructions on dev-site. To provide recommended directions to use calendar-filter component.

**Comment by supreethmr** [comment]
Since Calendar Filter component just face up component and acts as container for lot of smaller elements like navigation button, drop-down and days inside it. So would like to know do we need onFocus and onBlur handlers for Calendar Filter component and also would like to know if there are any scenarios where might need OnBlur and Onfocus Event on Calendar container.

cc: @benbcai  @neilpfeiffer

**Comment by neilpfeiffer** [comment]
> [...] do we need onFocus and onBlur handlers for Calendar Filter component and also would like to know if there are any scenarios where might need OnBlur and Onfocus Event on Calendar container.

I do not believe that there is any reason to expose `onFocus` and `onBlur` event handlers - the primary event that will be utilized will be `onChange`. This implementation should not reveal/expose that it has an input or functions like it has one, so there is never a time your are actively going "in" or "out" the component -- instead it should just be treated like a collection of buttons, waiting for a user to push/select them.

@benbcai feel free to correct or add-on if you have additional comments.

**Comment by benbcai** [comment]
@neilpfeiffer @supreethmr I agree that there isn't a need for onFocus and onBlur for CalendarFilter. 

The tech design above stated to get rid of `onChange` since we already have `onSelect` which is called whenever a date is selected. I now actually prefer `onChange` over `onSelect` for two reasons.
1. `onChange` is probably more standardized and commonly understood.
2. One difference between `onChange` and `onSelect` is that `onChange` currently returns the additional [metadata](https://github.com/cerner/terra-framework/blob/27aad52f858a4a409a707438a901f357736a9de6/packages/terra-date-picker/src/DatePicker.jsx#L196-L215) which includes `iSO`, `inputValue`, `isCompleteValue`, `isValidValue`. 

Here is an example:
`{iSO: "2020-05-13", inputValue: "05/13/2020", isCompleteValue: true, isValidValue: true}`

The last two options will always be `true` when selecting a date. Although `inputValue` sounds irrelevant for CalendarFilter, I think consumers can make use of the `inputValue` if needed since it is already formatted based on the locale. So this is readily available in case it is ever needed.

**Comment by jeremyfuksa** [comment]
I'm noticing that screen readers are reading the dates correctly RE: #1182, but the prev/next color hasn't pulled across.
