### ISSUE TITLE
[terra-application-navigation] Rollup Nav Item Selection Jumps Page

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-framework#1102]
# Bug Report

## Description

When selecting an item from the navigation option when the navigation tabs are collapsed, the rendered content jumps on the page.

## Steps to Reproduce

1. Go to terra-ui.com or https://engineering.cerner.com/terra-framework/raw/tests/terra-application-navigation/application-navigation/stated-demo
2. Adjust viewport to collapse navigation into rolled-up menu
3. Select different menu item to re-route
4. See page jumping

## Additional Context / Screenshots

https://share.getcloudapp.com/wbu0bApA
https://share.getcloudapp.com/5zu1Nejv

## Environment

* Browser Name and Version: Chrome Version 80.0.3987.163 
* Operating System and version (desktop or mobile): macOS Mojave 10.14.6

**Comment by emilyrohrbough** [comment]
actually, it looks like it's an issue with the secondary navigation not presenting when already within that navigation tab: https://share.getcloudapp.com/E0ubj7dp

In this video, I am on the Tests tab. I am trying to change the test page & it's not displaying the other test page options.

**Comment by supreethmr** [comment]
I am not sure whether this has been fixed or it happens at specific viewport widths but it-seems to be working fine. I tested same test example that is given in issue description page navigation was happening without jump as shown in the above video links. 

![application-navigation-jump-issue](https://user-images.githubusercontent.com/12869809/80978421-a5924100-8e43-11ea-8ab8-49b06c50ba06.gif)

**Comment by emilyrohrbough** [comment]
@supreethmr did you try when the primary navigation also renders a secondary navigation?

**Comment by supreethmr** [comment]
> @supreethmr did you try when the primary navigation also renders a secondary navigation?

yes, I also tried the above scenario as well and I was not able to observe the page jump as shown in videos provided on Issue. But I noticed secondary navigation was not showing up on selecting same navigation item in primary navigation ( Clicking on Tests opens components list in secondary navigation but after selection of component secondary navigation closes and re-clicking the Tests tab again is not re-opening the secondary navigation ) .

**Comment by emilyrohrbough** [comment]
I messed around with it some more and I am still seeing this on a small viewport size. I wonder if it's related to the drawer functionality of terra-dev-site. It seems when it's a certain size, the drawer collapses the secondary nave and it doesn't open when navigation to a new main nav: 
https://share.getcloudapp.com/lluDEvNW

**Comment by supreethmr** [comment]
>  It seems when it's a certain size, the drawer collapses the secondary nave and it doesn't open when navigation to a new main nav

I tested this with all view ports and secondary navigation opens on each new main navigation item select. as Shown in above attached video secondary navigation was not opening on re-selecting main navigation item `tests`. This is because of condition `  if (activeNavigationItemPath !== navigationItemKey) ` in [_DevSiteNavigation.jsx](https://github.com/cerner/terra-dev-site/blob/master/src/navigation/_DevSiteNavigation.jsx#L163) which will prevent router from update when the navigation item path is same.

I am still not able to reproduce the jump behavior ( it looks like dark overlay opens and closes fast on main navigation item select ). let me know if there are any specific width in which i can try to reproduce this issue. 

by Seeing the video attached I did check application navigation code to see if there any CSS transitions that might be causing this Blink behavior on page selection. I found that we have transform style defined for [drawer menu ](https://github.com/cerner/terra-framework/blob/b123efc4132de8e1b2235bd3e6a0e7dbbf4ae032/packages/terra-application-navigation/src/ApplicationNavigation.module.scss#L62). So in order to check this options I need help on reproducing it consistently.

**Comment by emilyrohrbough** [comment]
@supreethmr, Ryan asked me to take another look at this issue since it's been awhile. Since logging this, my chrome version has updated from  80.0.3987.163 to 83.0.4103.61 and I am no longer able to re-produce this issue. Not sure if it was a browser issue or a browser + external monitor issue but it seems to have resolved itself. I am going to close this. If it re-appears, we can re-open/log a new issue. 😄  Thanks for looking into this!
