### ISSUE TITLE
Focus not properly returned after navigation prompt on primary navigation item.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-framework#1120]
# Bug Report
## Description
Focus not properly returned after navigation prompt on primary navigation item.
Instead of returning focus to the selected item, focus is returned to root.

## Steps to Reproduce
1.  Navigate to: http://engineering.cerner.com/terra-application/raw/tests/terra-application/application-navigation/application-navigation-test
2. Enable the pending action.
3. Select Page 2 primary navigation item
4. Reject the navigation prompt (continue editing)

Expected: Focus is returned to primary navigation item 2.
Actual: Focus is returned to root.

This can be demonstrated by pressing tab after step 4.

## Additional Context / Screenshots
Also technically when accepting a navigation prop on a primary navigation item, focus should be sent to main, not returned to the primary navigation item.

## Expected Behavior
Expected: Focus is returned to primary navigation item 2.
Actual: Focus is returned to root.

## Possible Solution
![](https://media.giphy.com/media/12ETcAyWE6TjHy/giphy.gif)

## Environment
* Component Name and Version: terra-application
* Browser Name and Version: Chrome latest
* Node/npm Version: un-related
* Webpack Version: un-related
* Operating System and version (desktop or mobile):

## @ Mentions
@tbiethman

**Comment by ShettyAkarsh** [comment]
Transferred this issue to framework. as the issue exists in terra-application-navigation component.

**Comment by neilpfeiffer** [comment]
From the UX perspective, everything has been correctly captured in the initial issue description with the steps to reproduce and detailed expected behavior. Hattip @mjhenkes 

When the user selects a navigation item and is prevented from immediately navigating there as a result of the NavigationPrompt (or similar):
- if the reject/go-back option is chosen by the user (e.g. the navigation request is completely blocked by selecting "Continue Editing" from the NavigationPrompt), the action is cancelled and the user returns to the prior state of the application, where focus should be returned to the triggering element,
- if the accept/go-forward option is chosen (e.g. the user selects "Don't Save" from the NavigationPrompt), the navigation request continues, navigation occurs, and focus is placed on main in accordance with how navigation works when unimpeded.
