### ISSUE TITLE
[terra-abstract-modal] Focus switches between controlled inputs inside a modal

### ISSUE THREAD

**Issue by bbennett0** [cerner/terra-framework#1123]
# Bug Report

## Description
When using controlled inputs inside a terra modal, focus when typing in the inputs changes unexpectedly. When you first type in an input, it immediately loses focus, and if you then type into another input, each character will switch focus between that input and the previous input.

Demo: https://codesandbox.io/s/terra-modal-input-bug-11p3s?file=/src/index.js

Commenting out the AbstractModal in the example will show correct behavior.

## Steps to Reproduce (using example above)
1. Type in one of the inputs - it will lose focus after typing.
2. Select the other input, and type a character - after typing, focus will switch to the other input.
3. Keep typing - focus will again switch back and forth between the inputs.

## Additional Context / Screenshots
https://i.imgur.com/Xl2WWWU.gifv

## Expected Behavior
Typing in inputs should not switch focus to another input when inside of a modal.

## @ Mentions
@tbiethman

**Comment by tbiethman** [comment]
I think this is a one-liner: https://github.com/cerner/terra-framework/blob/master/packages/terra-abstract-modal/src/AbstractModal.jsx#L91

React has two ref-related functions on it: `createRef` and `useRef`. Both are functions that return an instance of a `ref` object. However, the former creates a new object every time it is called. The latter is a hook that provides a the same object reference throughout the life of the calling component.

The logged issue results from our usage of the ref's reference identity [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-abstract-modal/src/_ModalContent.jsx#L98) in an effect to manage focus management. Since we call `createRef` every time the AbstractModal is rendered, that effect executes and starts focusing things like crazy. We really only intend for that effect to be executed once (and cleaned up once).

The solution to this problem is to use `useRef` instead of `createRef` in the AbstractModal. I really wish these were named more differently.
