### ISSUE TITLE
[terra-application-navigation] Side drawer does not open in IE 11 on tiny form factor

### ISSUE THREAD

**Issue by mschile** [cerner/terra-framework#1161]
# Bug Report

## Description

The side drawer does not open on the tiny form factor in IE 11.

## Steps to Reproduce

1. Load https://engineering.cerner.com/terra-ui/home/terra-ui/index in IE 11
2. Resize to tiny form factor
3. Try to open side drawer
## Expected Behavior

Side drawer opens.

## Environment

* Component Name and Version: terra-application-navigation
* Browser Name and Version: IE 11
* Operating System and version (desktop or mobile): Windows Server 2016 Standard

## @ Mentions

@tbiethman

**Comment by tbiethman** [comment]
I believe the issue stems from the calc statements within these translations: https://github.com/cerner/terra-framework/blob/master/packages/terra-application-navigation/src/ApplicationNavigation.module.scss#L61,L75

IE10/IE11 cannot parse them, which means no translation actually occurs and the drawer doesn't appear to open.

To fix this, we'll have to combine multiple translations in sequence:
```css
transform: translate3d(100%, 0, 0) translate3d(-3.571rem, 0, 0);
```

However, that calls into question our `--terra-application-navigation-content-layout-default-width` value, which by default is a calc. But even a fixed value would need to be inverted using calc for the `rtl` implementation, which is also unsupported: https://github.com/cerner/terra-framework/blob/master/packages/terra-application-navigation/src/ApplicationNavigation.module.scss#L73

So far as I can tell, we'll need to talk about removing the themeable variables for these widths in order to fix this. It doesn't seem like a deal breaker if it results in more browser support. The alternative isn't very pretty (JS-driven inline styles to calculate the transforms based off of intrinsic widths).

**Comment by ryanthemanuel** [comment]
Discussed this in scrum with @tbiethman and @neilpfeiffer. Let's get rid of the themeable variable in this case to fix the issue as @tbiethman suggested above.

**Comment by emilyrohrbough** [comment]
@tbiethman do you believe this is caused by the nesting of the calc within transform that it's being incorrectly handled by the browser? The notification-dialog seems to use the theme var + calc successfully for width: https://github.com/cerner/terra-framework/blob/master/packages/terra-dialog-modal/src/DialogModal.module.scss#L60

**Comment by tbiethman** [comment]
@emilyrohrbough calc _is_ broadly supported in IE10/IE11, so that width example should be fine. The issue here is that the calc is being used inside the translate, which is not supported in those browsers.
