### ISSUE TITLE
[terra-application-navigation] Notification count changes size of nav bar and shifts text

### ISSUE THREAD

**Issue by lawsonjames** [cerner/terra-framework#1163]
# Feature Request

## Description

The top navigation bar has a different height and the text jumps significantly when going from a state of no notification counts to having counts, or vice versa. As a consumer, I am requesting that the height of the top navigation bar stay the same and the text stay in the same position regardless of the presence of notification counts.

## Additional Context / Screenshots

<img width="1904" alt="1" src="https://user-images.githubusercontent.com/14286414/85628225-64453300-b635-11ea-96e6-ab8ecc808fd6.png">

<img width="1904" alt="2" src="https://user-images.githubusercontent.com/14286414/85628268-7cb54d80-b635-11ea-9a32-256a2d12cc90.png">

**Comment by sethbroox** [comment]
@lawsonjames, The intent of the design, and thus the functionality of the code, was that if your application ever needed/could have counts - then you use the count version. This aligns the text in the Top Tabs to the bottom of the tab to allow space for the Count to show up. This means that the text is always at the bottom, even if at the moment there are no Counts present. This reduces the flicker/shifty behavior when counts are coming and going.

So instead of flipping out to the No Counts version, you always use the counts version. Doing would mean that you should not be seeing any height shift.

@dkasper-was-taken, can speak to this from a technical perspective.

**Comment by lawsonjames** [comment]
@sethbroox I'm a little confused by your references to different "versions" of this component. The behavior I'm seeing is caused by the 'notifications' prop either being populated with 0 or a number greater than 0 for any given navigationItem.

**Comment by dkasper-was-taken** [comment]
@lawsonjames @sethbroox Looks like an oversight on my part. The logic for having a notification, and having a visible notification count needs to be split out.
https://github.com/cerner/terra-framework/blob/master/packages/terra-application-navigation/src/tabs/_Tabs.jsx#L316

Here is a branch with the proposed changes:
https://github.com/cerner/terra-framework/compare/correct-nav-notifications
