### ISSUE TITLE
[terra-date-time-picker] Focusing on Time Input does not clear Invalid default value

### ISSUE THREAD

**Issue by avinashg1994** [cerner/terra-framework#1217]
# Bug Report

## Description

When an **Invalid default date and time value** is specified, then focusing on the "Time Input", only clears the time input and not the date value.

## Steps to Reproduce

1. Goto https://engineering.cerner.com/terra-framework/tests/terra-date-time-picker/date-time-picker/date-time-picker-default-date-excluded
2. Click on the `hour/minute` input of the time input.
3. Notice that only the time input value gets cleared and not the date input value.
4. Whereas on refreshing and focusing on the date input, clears both the date and time input values.

Similarly can also be reproduced on https://engineering.cerner.com/terra-framework/tests/terra-date-time-picker/date-time-picker/date-time-picker-default-date-out-of-range

## Expected Behavior

Focusing on the "Time Input" should clear the entire date and time value when an invalid **default** date and time value is specified.

**Comment by benbcai** [comment]
In this workflow the date value is correctly cleared [here](https://github.com/cerner/terra-framework/blob/ca8fde828d309978e69ab801d59044f5e71626b0/packages/terra-date-time-picker/src/DateTimePicker.jsx#L467). However, a null date value fails to update the date state in the date picker due to this [if check](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/DatePicker.jsx#L186) for a valid date. The date state should always be updated even with a null date value in the case for clearing the date.
