### ISSUE TITLE
[terra-date-time-picker] onClickOutside callback event does not get triggered

### ISSUE THREAD

**Issue by avinashg1994** [cerner/terra-framework#1219]
# Bug Report

## Description

`onClickOutside` callback event does not get triggered when the calendar dropdown is closed by clicking outside it.

## Steps to Reproduce

1. Goto https://engineering.cerner.com/terra-framework/components/terra-date-time-picker/date-time-picker/events
2. Scroll down to the event example and click on calendar button to open the dropdown calendar.
3. On clicking outside of the calendar dropdown does not trigger onClickOutside event callback and the counter also does not increment.

## Expected Behavior

Clicking outside the calendar dropdown should trigger the onClickOutside callback event.

**Comment by benbcai** [comment]
The `onClickOutside` feature is provided by [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) which wraps the Calendar into [WrappedCalendar](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/react-datepicker/index.jsx#L45). This API used to be available for both the portal and popup version of the picker. With this [change](https://github.com/cerner/terra-framework/pull/701/files#diff-0eaf044a5babfc8ff56c4b57c5220edbR461-R570),   `onClickOutside` is now only available for the portal version and not popup. I do not remember what the reason was for this. Anyone remember?

**Comment by benbcai** [comment]
Perhaps, this [change](https://github.com/cerner/terra-framework/pull/701/files#diff-0eaf044a5babfc8ff56c4b57c5220edbR461-R570) to not wrap the popup picker with react-onclickoutside is due to the following two issues:

1. If wrapped with react-onclickoutside, clicking on the arrow of the attachment point would close the popup since this arrow is considered outside of the popup.
![Screen Shot 2020-08-18 at 2 51 37 PM](https://user-images.githubusercontent.com/22618655/90560849-57404e00-e165-11ea-8175-7c23411462cb.png)

2. If wrapped with react-onclickoutside, the `onClick` event in [_PopupOverlay](https://github.com/cerner/terra-framework/blob/4880772b8b92bb05f99ef3f3084a8d1e4c389bdc/packages/terra-popup/src/_PopupOverlay.jsx#L43-L48) does not get triggered and as a result the `onRequestClose` callback will not be executed for the consumer. The cause of this may be because react-onclickoutside has its own overlay on top of ours which eats up our onClick event handler.

Due to the above two issues (especially the second one), we probably should not wrap the popup picker with react-onclickoutside. A viable solution could be to check the type of event in date picker's [handleOnRequestClose](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/react-datepicker/index.jsx#L425) fired from terra-popup. There are three type of events that terra-popup fired 'onRequestClose'.

1. `keydown` when pressing the `ESC` key to close the popup.
2. `resize` when resizing the container to close the popup.
3. `click` when clicking outside to close the popup.

Date picker's [handleOnRequestClose](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/react-datepicker/index.jsx#L425) could check the event type of `click` and do the same thing as [handleCalendarClickOutside](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/react-datepicker/index.jsx#L500-L506)

**Comment by benbcai** [comment]
The `onClickOutside` callback is triggered when clicking outside to dismiss the picker. The usefulness of this api is limited since the picker is also dismissed after selecting a date. A more useful api for common use cases would be an `onDismiss` callback triggered whenever the picker dismisses, regardless clicking outside or selecting a date.

After further discussion with the Terra team, we will do the following to address this issue:

- [ ]  Introduce a new prop called `onDismiss` whenever the picker closes.
- [ ]  Leave `onClickOutside` the way it behaves today, despite the reported issue that it is not invoked for the popup picker. Consumers are recommended to use the new `onDismiss` if they encounter the reported issue. 
- [ ]  Label the `onClickOutside` prop as `**Deprecated**`. It will be removed in #1222 as part of the next major version.
- [ ]  The implementation to invoke `onDismiss` can be done in [setOpen](https://github.com/cerner/terra-framework/blob/e63c8c8ba6484d5122b9fb128973ce894ed733df/packages/terra-date-picker/src/react-datepicker/index.jsx#L462-L467) by checking the `open` argument equal to `false` indicating that the picker is dimissing.
