### ISSUE TITLE
[Terra-Date-Input] Restrict year input to be within 1900 and 2100

### ISSUE THREAD

**Issue by ShettyAkarsh** [cerner/terra-framework#1238]
We are currently restricting the day input to be within 1-31 in Terra-Date-Input. similarly we should do it for year input as well to be within 1900 and 2100.

![DateYearInput](https://user-images.githubusercontent.com/45097016/92881359-87a99e00-f42c-11ea-85a7-6ad1ff42d403.gif)

**Comment by saket2403** [comment]
Currently values from 1 to 9999 are accepted as year input. I have made changes to accept values 1900-2100 only. 
One question I had regarding this is, if user moves out of the year input (onBlur) after entering an invalid value should we clear out the year value or default it to min Value 1900.
![DateInput](https://user-images.githubusercontent.com/42207428/94140801-6c597c80-fe89-11ea-9938-4428eef50cd0.gif)
Your thoughts @benbcai

**Comment by benbcai** [comment]
@saket2403 I don't think it should default to 1900 onBlur after an invalid value is entered because 1900 mostly like is not what the user intended to enter and that he/she may not be aware that it got updated to a different value. Clearing the invalid value may be a bit annoying to the user when he/she may intend to come back immediately to fill in the remaining digits to complete the entry.

terra-time-input has logic to prepend a zero to auto complete the hour/minute/second when the user enters just one digit. For example, entering `5` for the hour would get updated to `05` onBlur because there is less ambiguity on what the user intends to enter. I don't think the same assumption can be made here for the year. If the user enters just `20` and it loses focus, we can't make the assumption on whether the user intends to enter `2000` or `2020`.

I think we should just leave the entry as is when it loses focus and not do anything with it.

Not sure if @neilpfeiffer or @jeremyfuksa has other thoughts.

**Comment by jeremyfuksa** [comment]
It would definitely be better from a safety standpoint to do nothing rather than inject an erroneous, unexpected, and possibly unnoticed year.
