### ISSUE TITLE
Z index property for Modal component when using disclosure manager.

### ISSUE THREAD

**Issue by leducquan** [cerner/terra-framework#1373]
# Feature Request
Allow a way to modify z-index of Modal component when using Disclosure Manager.

## Description
Allow for a zIndex property for the Modal Component to be modified or to have the modal component to have a max z-index.

I've attached a screenshot of the interaction and the issue that is being caused and the z indexes for reference.

We require the modal to have a higher precedence than the popup.

## Additional Context / Screenshots
![after5](https://user-images.githubusercontent.com/19377430/107522825-fe012680-6bab-11eb-8b15-5a752b9d429b.gif)
![image](https://user-images.githubusercontent.com/19377430/107523025-386ac380-6bac-11eb-8f9d-6db6b3b07e26.png)

**Comment by tbiethman** [comment]
I think there's a couple things going on here.

1. You should likely be using the [NavigationPrompt](https://engineering.cerner.com/terra-ui/components/terra-navigation-prompt/navigation-prompt/about) to notify your users that they're taking a destructive action. This will present a more consistent UI and allow you to integrate more easily with other applications that use the NavigationPrompt. I do not recommend using the ModalManager to present your own custom dialog.

2. The NavigationPrompt handler will present a NotificationDialog, which has a z-index of 9000 and will render over your Popup....

3. ...but the Popup today has some limitations with content being presented over it. It includes a focus trap and other accessibility features that will limit user interaction with the dialog on top of it. This is intended to be fixed in the future, but in the meantime, you will need to dismiss the popup prior to showing your dialog.
