### ISSUE TITLE
Misaligned arrow controls for IE browser

### ISSUE THREAD

**Issue by JB016205** [cerner/terra-framework#1401]
# Bug Report

## Description
Visual alignment issue with the calendar filter for terra-date-picker and terra-clinical-onset-picker; based on our investigation we believe the issue is with the framework component. I was unable to recreate this for Edge or Chrome, but wanted to get the issue logged in case it was deemed important enough to correct. 

## Steps to Reproduce
1. Render the date picker within the orion-fusion-theme.
2. Open the calendar-filter
3. Arrows are misaligned under that theme.

## Additional Context / Screenshots
![screenshot-1](https://user-images.githubusercontent.com/3382775/114582931-ae3fe980-9c46-11eb-9aff-1403d3a60ebb.png)

## Expected Behavior
Arrows should be aligned properly in supported themes. 

## Possible Solution
The arrows themselves may be sized incorrectly for the theme. Another image or potentially resizing as part of the theme may be appropriate but these are just guesses at this point. 

## Environment
* Component Name and Version: terra-date-picker (via terra-clinical-onset-picker)
* Browser Name and Version: IE10 (Tested against Chrome and Edge, issue was not present)
* Node/npm Version: 
* Webpack Version:
* Operating System and version (desktop or mobile): Desktop, Windows

**Comment by saket2403** [comment]
I checked the date picker with orion fusion theme on IE, the arrows look fine to me. Are you using the latest version of the date picker. 
![Capture](https://user-images.githubusercontent.com/42207428/115846969-127d5d00-a440-11eb-8264-72f7e0393aa2.PNG)

**Comment by neilpfeiffer** [comment]
@JB016205 Can you provide more details as to where your originating screenshot came from (you mentioned you were unable to recreate it in Edge or Chrome) to help us recreate the alignment issue?

- What version of the date-picker are you using? (looks to be version 4.47.0 or newer)
- What Windows environment are you seeing this in? (e.g. local with a VM, or Citrix + development domain, etc.)
- What edition of Windows (if local), or Windows Server (for a specific Citrix box) are you seeing the issue?

**Comment by benbcai** [comment]
Not certain if the component in the originating screenshot is ion-condition-js since it one of only few components using terra-clinical-onset-picker and displays the "Confirmation" and "Laterality" field names. If ion-condition-js is the component, then it should using terra-clinical-onset-picker 4.28.0 which uses the latest terra-date-picker 4.59.0.

I also was unable to recreate using the onset-picker in Terra-ui on IE10 with orion-fusion-theme.

@JB016205 With the environment you're usiing, are you able to recreate using an onset-picker example on [Terra-ui](https://engineering.cerner.com/terra-ui/components/terra-clinical-onset-picker/clinical-onset-picker/clinical-onset-picker)?

**Comment by JB016205** [comment]
Just seeing these comments, apologies. I'll see if we can take another look with the newer versions. This was ion-conditions-js and was done within a specific Internet Explorer setting.

If we want to get a few people in contact we can do so.
