### ISSUE TITLE
Date and Date/Time Picker Crashes When Navigating to an Upper or Lower Bound Month

### ISSUE THREAD

**Issue by JW069532** [cerner/terra-framework#1405]
# Bug Report

## Description

When navigating to January 1900 or December 2100 in the `terra-date-picker` or `terra-date-time-picker`, the following error is thrown and causes the page to stop rendering while using Internet Explorer 10/11.

- Note: It only occurs when you navigate the months with the arrows while on the year 1900 or 2100. If you select January/December and then change the year, it behaves as expected.

```
TypeError: Unable to get property 'hasAttribute' of undefined or null reference
```

https://user-images.githubusercontent.com/83246901/116145328-d1d14e00-a6a2-11eb-8728-281a20fe6e19.mp4

## Steps to Reproduce

1. Open Date or Date/Time Picker
2. Select 1900 as the year
3. Use back arrow to set the month to January

**OR**

1. Open Date or Date/Time Picker
2. Select 2100 as the year
3. Use forward arrow to set the month to December

**Note:** It is reproducible from the terra-dev-site page for Terra in IE.
https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/date-time-picker

## Additional Context / Screenshots

See video demo above.

## Expected Behavior

The arrows should navigate to January of 1900 and December of 2100.

## Environment

* Component Name and Version: terra-date-time-picker@4.60.0 **and** terra-date-picker@4.59.0
* Browser Name and Version: Internet Explorer 10 & 11
* Node/npm Version: Node v10.22.1/NPM 6.14.6
* Webpack Version: 4.41.5
* Operating System and version (desktop or mobile): Windows 7/10 and Windows Server 2012/2016

## @ Mentions

@benbcai

**Comment by benbcai** [comment]
The error occurs on this [line](https://github.com/cerner/terra-framework/blob/6a636ae62c4b9cddeb8637313e4752d1e80b1d49/packages/terra-date-picker/src/react-datepicker/day.jsx#L220) when accessing the document's activeElment. The Previous month button will be hidden when the month shown is the earliest supported month (January 1900) because it doesn't allow to navigate before this month. Likewise, the Next month button will be hidden when the month shown is the last supported month (December 2100).

When focus was on either the Previous or Next month button and the button becomes hidden, the active element would be set to `<body>` on other browsers but [set to null in IE](https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement#value), which then causes this issue. 

We should just be able to check for the existence of the activeElement in this case since we would never run into this scenario when the active element is the calendar button.
