### ISSUE TITLE
Add ability to open an external link from terra-application-layout primary and secondary navigation

### ISSUE THREAD

**Issue by Mahmud-Khan** [cerner/terra-framework#228]
# Feature Request
Terra Application Layout provides options to navigate internal paths through the primary(tabs) and secondary(side menu) navigation items. For some use cases, the user may need to be redirected to an external link.
### Issue Type

- [ ] New Component
- [x] Enhancement
- [ ] Bug Fix
- [ ] Tech Only

## Description
Clicking primary or secondary navigation item with external path would open a new tab with the external path like the example below.
![terra-application-layout_ext_link](https://user-images.githubusercontent.com/21693381/42905214-583dbbb2-8aa5-11e8-886d-7201930953a3.gif)

## Expected Behavior
Ability to open an external link in a new tab.

## Current Behavior
Only allows navigating to an internal path.

**Comment by Mahmud-Khan** [comment]
@mjhenkes  @nickpith As part of a Q3 commitment I have started working on this issue. For the primary navigation tab adding an isExternal prop to the [application links](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/ApplicationLinks.js) and creating an anchor tag for external link instead of the button in [ApplicationTab](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/_Tab.jsx) would solve this. Side menu items also need to create anchor tag for external links. Please let me know whether this is the right approach. Thank you.

**Comment by nickpith** [comment]
I don't see the reasoning why the rendered item should change from a button for the tabs or side menu. All this is wanting to do is change the click behavior based on the nav item or menu item. Using the tab as an example, I assume the [handleOnClick](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/_Tab.jsx#L86-L92) should be able to determine if this is a URL (aka not a path) and what the target should be then feed that into a [window.open()](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) call just like how it is doing a `history.push` now. We may want to add 2 new props (url & target) because I not sure if we want to change up the meaning of the existing path prop. That discussion is probably more important at the `navigationItems` prop of the application-layout. Then we can work our way down into the internal components once we figure out what the external component should expect.

The same thing would apply for the side menu items. It should just call `window.open()` if it is a external application link.

**Comment by mjhenkes** [comment]
I suggest using a leaving the current navigation as is and instead adding in a redirect component that will take you to the external link when you render it. This approach would allow you to add any additional logic that a consumer may want before redirecting to another site. For example, you could optionally put up a warning message that you are about to leave the current site etc.

This would be a very similar pattern to what we have in place for selecting the first item in the side menu. I'm not sure the react router redirect component handles external links but a react redirect component would be easy to make.

Here's an example of what the routing config might look like.
```javascript
...
      '/thirdPartySite': {
         'path': '/thirdPartySite',
         'component': {
            'default': {
               'componentClass': Redirect,
               'props': {
                  'to': 'https://www.thirdpartysite.com', 
               }
            }
         }
      },
...
```

**Comment by Mahmud-Khan** [comment]
If a redirect component is used, the external link will be opened in the content area of the application layout. Is that right? or The redirect component will be opened in a new window.

**Comment by nickpith** [comment]
The new window can be solved by the component we are redirecting to. I almost have something working so I'll comment back soon with a rough idea approach.

**Comment by Mahmud-Khan** [comment]
In the second approach mentioned above, we are using react-router for redirecting to an internal route and then the corresponding component handles opening the external link to a new window or tab. The component also needs to reset the current path to the last internal route. Isn't it simpler to just create an anchor tag with target valued as _blank or use window.open for opening a new tab for the external link? This way we let the browser handle the external link since it does not need the context of the current application route or history.

**Comment by dkasper-was-taken** [comment]
A little experimentation looks using the location works.
```
window.location.replace('http://my-example.com'); 
```

**Comment by nickpith** [comment]
@dkasper-was-taken and I talked and I explained the main use case which is to open in a new window/tab and that still creates unwanted side effects.

**Comment by nickpith** [comment]
@Mahmud-Khan Please work with @dkasper-was-taken offline to come up with an approach / design to present back on this issue for the group.

**Comment by Mahmud-Khan** [comment]
@nickpith Thank you. I will work with @dkasper-was-taken.
