### ISSUE TITLE
Notification dialog doesn't account for additional focus trap sources within a modal manager

### ISSUE THREAD

**Issue by SushmithaBN** [cerner/terra-framework#247]
# Bug Report

## Description
Not able to select the date in DatePicker (which is the form is having notificationDialog implemented) inside a modal.
If I remove the releaseFocus and requestFocus from NotificationDialog- It works fine, but on the other hand I cannot perform actions in notificationDialog.
**The render caused by requesting focus is causing the notification dialog to re-render and mistakenly remove focus.**

Sample code:
https://gist.github.cerner.com/SB054668/19767a68a996d4cfe05cdeee700acad3
Actual code:
https://github.cerner.com/SupplyChain/po-filter-js/blob/SUPPLYCHN-3394/src/po-filter/components/PoFilterView.jsx

## Steps to Reproduce

1. Open modal window - which includes a form containing notification dialog and date picker.
2. Try to click on date in modal window, date gets selected
3. Now try to close the modal window, prompt the user with Notification dialog
4. Now try to proceed using Ok button, Notification dialog does not close. 

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/42537313/44332775-8d6d6900-a48a-11e8-8d31-f484621ac9d6.png)
![image](https://user-images.githubusercontent.com/42537313/44385890-6a03f600-a53e-11e8-807a-dc8d5ebce9ea.png)

## Expected Behavior
Focus should get released/trapped when notification dialog is used with date picker in modal.

## Environment

* Component Name : Notification Dialog and Version: ^1.5.0
* Browser Name: Chorme and Version: 68.0.3440.106 (Official Build) (64-bit)
* Node/npm Version: [e.g. Node 8/npm 5]
* Operating System and version (desktop -MAC):

**Comment by dkasper-was-taken** [comment]
The root cause of the issue is this function:
https://github.com/cerner/terra-framework/blob/master/packages/terra-notification-dialog/src/NotificationDialog.jsx#L138

The life cycle that causes this issue is notification dialog is mounted but not open. This initial state, causes no problems. Following this, if another component with focus management is presented, whether that be another notification dialog, a date picker, or a popup, that component will request focus.  This will trigger a state change within the modal manager, which will trigger another render.  As the render traverses the tree the "componentDidUpdate" function will be called within the notification dialog, and it's logical checks then make a call to release focus, removing it from the other component that had initially requested it.

The following is an example solution:
```
  componentDidMount() {
    if (this.props.isOpen && this.props.requestFocus) {
      this.props.requestFocus();
    }
  }

  componentDidUpdate(prevProps) {
    if (this.props.isOpen) {
      if (!prevProps.isOpen && this.props.requestFocus) {
        this.props.requestFocus();
      }
    } else if (prevProps.isOpen && this.props.releaseFocus) {
      this.props.releaseFocus();
    }
  }

  componentWillUnmount() {
    if (this.props.isOpen && this.props.releaseFocus) {
      this.props.releaseFocus();
    }
  }
```
