### ISSUE TITLE
Add appropriate roles to terra framework components for Accessibility.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#267]
# Bug Report

## Description
For our layouts to be accessible, we should do the following.

- Add role="main" to the main node inside application layout
- Add role="banner" to the application header
- Add role="navigation" to the links inside the application header, and the sidebar utility.

**Comment by supreethmr** [comment]
Links inside application header are application links which has given role as 'link'. Do we still need to change it to 'navigation' for links inside application header. 
If the role change from 'link' to 'navigation' is not required then for side bar utility Items also we can have role as 'link' instead of 'navigation. @JakeLaCombe  Please share your thoughts on this.

**Comment by JakeLaCombe** [comment]
The parent container is what needs role navigation, not the links themselves. Sorry for the confusion
