### ISSUE TITLE
Terra Utility Menu needs to have the option to switch it's role.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-framework#272]
# Bug Report

## Description
The Terra Utility Menu is not always designed to be a navigation component. In our dev site for example, it's used as a menu. To ensure screen readers do not always read this as a navigation menu, we need to allow for the developer to change the value of role. We can default it to "navigation" for passivity purposes.

https://github.com/cerner/terra-framework/blob/01daffb58489853b7663bd406ba0dbd53df96e46/packages/terra-application-utility/src/utility/_UtilityMenu.jsx#L364

**Comment by yuderekyu** [comment]
### Tech Design
Add new prop `menuRole` to ApplicationMenuUtility and ApplicationHeaderUtility components. This allows a developer to change the value of role.

| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| `menuRole` | string | 'navigation' | Set the menu's role for accessibility. |

**Comment by bjankord** [comment]
I think for this, we'll want to move the role attribute onto the `UL` element.
<img width="956" alt="screen shot 2019-02-11 at 2 35 32 pm" src="https://user-images.githubusercontent.com/633148/52592144-404fcb80-2e0b-11e9-8f85-c738196233f8.png">

The latest version of axe warns that the UL element inside of terra-utility, "must only directly contain `<li>`, `<script>` or `<template>` elements". 

I believe this issue is from the `role="button"` attributes on the `li` element. If we update the `ul` role to navigation or menu, it resolve the axe warning and seems to be more inline with the intention of the `<li role="button" />` markup.

**Comment by supreethmr** [comment]
I would like to know can we have role at both utilitymenu and ul tag so that it will help user in terms accessibility as screen readers will read the role even when we click on outer div of ul tag which is content container in case of utility menu. Since keeping the role only at ul tag will make screen readers to read role only when we click on menu items and not on click of menu itself. Please share your thoughts on this. @JakeLaCombe

**Comment by JakeLaCombe** [comment]
That's an interesting axe issue. I'm looking at this issue, and it looks like role is actually attached to the container of the navigation, which is the outer div. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role

It almost feels like we should attach role="navigation" to the div, and role="menu" to the ul. Maybe that approach will resolve the issue?

**Comment by bjankord** [comment]
That sounds like worth trying. With that, we wouldn't need to add the proposed `menuRole` prop. cc/ @supreethmr let's move forward with Jake's idea noted above.

**Comment by supreethmr** [comment]
@bjankord Adding role = "menu to ul tag causing the Error "Required ARIA children role not present: menuitem menuitemradio menuitemcheckbox" while running WDIO on [Travis build](https://travis-ci.org/cerner/terra-framework/jobs/495567513).  but i haven't faced this error while running wdio in my local machine. Menu-Item has given role button / note 
I observed that changing role of ul tag to "Navigation" will not throw this error and it passes all WDIO on travis build.  
I suspect it is due to axe rules role menuitem, menuitemradio and menuitemcheckbox should not have parent role as menu. Please share your thoughts on this.
