### ISSUE TITLE
[terra-slide-panel-manager] The SlidePanelManager should set focus to the panel when opened

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#321]
# Feature Request

## Description
To better align ModalManager and SlidePanelManager behavior, we will set focus to the SlidePanel's panel container when the SlidePanelManager is triggered open.

Changes will also be required in the SlidePanel to expose a ref to the panel container.

## Additional Context / Screenshots
See issue: https://github.com/cerner/terra-core/issues/1973

**Comment by supreethmr** [comment]
Slidepanel has two content regions main-content and panel-content. panel-content will hold the components / contents that will be displayed on slide panel on Open.
Focus to slidepanel can be set on open by calling focus() method for panelNode in preparePanelForTransition() method. Since preparePanelForTransition() method displays slidePanel  code "this.panelNode.focus()" is added to set the Focus for Panel. onClose of side panel Focus will be setBack to main-content by calling focus() method for panelNode in  handleTransitionEnd() method. 

Since SidePanel is not Model Content focus will not be trapped inside panel focus will be return to main-content on close of side panel. 

@tbiethman Please share your thoughts on the code changes for above approach : https://github.com/cerner/terra-framework/commit/cd2e1cc44f665694b8299565f3cf5ef795c3483e

**Comment by tbiethman** [comment]
@supreethmr You're right, we're not going to be able to return focus to the exact element. However, I'm not sure if we want to reset focus to the first focusable element in the main-content on close, or if we want to just do nothing. @neilpfeiffer @bjankord @JakeLaCombe Any accessibility experts want to weigh in?

**Comment by bjankord** [comment]
@supreethmr's proposal sounds good to me 👍

**Comment by supreethmr** [comment]
Thanks @tbiethman  @bjankord . will go ahead and open PR with the fix stated above.
