### ISSUE TITLE
[Embedded Content Consumer] Terra-dev-site examples blank

### ISSUE THREAD

**Issue by tomleewu** [cerner/terra-framework#363]
# Bug Report

## Description
The examples of `terra-embedded-content-consumer` on terra-dev-site don't load in Firefox.

[Link](https://engineering.cerner.com/terra-core/#/components/terra-embedded-content-consumer/embedded-content-consumer/embedded-content-consumer)

## Steps to Reproduce

1. Open up Firefox
2. Head to this [link](https://engineering.cerner.com/terra-core/#/components/terra-embedded-content-consumer/embedded-content-consumer/embedded-content-consumer)

## Additional Context / Screenshots

<img width="810" alt="screen shot 2018-06-28 at 8 06 07 am" src="https://user-images.githubusercontent.com/17147005/42036230-793c2a3e-7aaa-11e8-88a1-78b74552adcf.png">

## Expected Behavior

Examples should appear as so:
<img width="796" alt="screen shot 2018-06-28 at 8 09 03 am" src="https://user-images.githubusercontent.com/17147005/42036304-b25b818e-7aaa-11e8-9f97-036b0e77ca58.png">

## Environment

* Component Name and Version: Embedded Content Consumer
* Browser Name and Version: Firefox 61
* Operating System and version (desktop or mobile): MacOS High Sierra

**Comment by emilyrohrbough** [comment]
This is a weird issue because we are need the provider examples to feed to the embedded-content-consumer examples for both doc and test pages. My proposal would be this:

1. Add a hidden `providers` navigation link to nav.config.js
2. Move `packages/terra-embedded-content-consumer/src/terra-dev-site/test/embedded-content-consumer/providers` examples to `packages/terra-embedded-content-consumer/src/terra-dev-site/providers`
3. Rename each example to from `example.test.jsx` to `example.provider.jsx`
4. Update both the doc and test urls to be the raw provider routes

Then, in the terra-ui repo, we can add the hidden providers navigation link to the nav.config.js and then these examples should be visible on terra-ui.com.
