### ISSUE TITLE
Spike on 12 hour time input in locales that use 24 hour format

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#384]
# Feature Request

## Description
The translation team has noted that `en-US`, `es-US`, and `ar` are the only locales from our supported locale list that should include 12 hour display. Some guidance is needed on how we should handle the 12 hour time input when the locale is set to one that only uses 24 hour time formatting. Currently, we display 12-hour input, with the final input for a.m./p.m. being empty. Logging an issue so we can spike on this with the translation team / UX team to figure out a reasonable solution.

**Comment by calebmeyer** [comment]
We are currently running into this problem. If you set a datetime picker to 12 hour format, but set your locale to en-GB, you get a date time picker with no am/pm that cannot select anything larger than 12:59

![image](https://user-images.githubusercontent.com/3342777/64885261-4750ed80-d629-11e9-8770-1a615253a649.png)

**Comment by bjankord** [comment]
Some options we've discussed

Putting preference on the locale over the time-format variant. e.g. If locale is set to a place that uses 24 hour format, but the variant is set to 12 hour format, the control would use the 24 hour format.

Another option is putting preference on the time format variant. e.g. If the locale is set to a place that uses 24 hour format, the control would display the 24 format display, unless the time format variant was set to 12 hour format, then it would display in 12 hour format.

**Comment by bjankord** [comment]
My preference is towards the later of the these two, I'm curious to hear what @benbcai and @mmalaker think on this.

**Comment by calebmeyer** [comment]
I went ahead and changed to 24 hour for en-GB and now we get an onChange event when you first click the time picker that has a value of empty string, and no further onChange events after that.

**Comment by benbcai** [comment]
I'm concerned that the former option would be considered a breaking change.

Isn't the latter option the current behavior? The default variant for both [date-time-picker](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-time-picker/src/DateTimePicker.jsx#L124) and [time-input](https://github.com/cerner/terra-framework/blob/master/packages/terra-time-input/src/TimeInput.jsx#L93) is the `TimeUtil.FORMAT_24_HOUR` so unless the consumer chooses to use the 12-hour format, 

The time-input does log out this [warning](https://github.com/cerner/terra-framework/blob/master/packages/terra-time-input/src/TimeInput.jsx#L144) for such scenarior:

`This locale only uses 24 hour clock. The ante meridiem and post meridiem will not be displayed`

**Comment by mmalaker** [comment]
Basically the time input needs to work properly in any supported locale. If the 12 format doesn't apply in a given locale, the input should allow time in the 24 hour format.

**Comment by calebmeyer** [comment]
I did some more testing, re my previous comment. I set an onBlur to see what would happen. Even though we're setting an initial value for the datetime picker (and that value is displayed correctly on the page), if you change only the time, no onChange is fired, and onBlur shows only the time, not the date. If you change the date and the time, it works correctly (even though a date is already set).

This is both for 12 hour and 24 hour time formats, and only in en-GB. It works correctly in en-US (changing either date or time is respected).

**Comment by mmalaker** [comment]
The purpose of the 12 hour variant is to allow users enter time in a familiar format for the locales that support it. I don't think the intention was to force 12 hour time entry in locales that use a 24 hour clock. But regardless, the time input has to function in any locale so I agree this sounds like a bug.

**Comment by benbcai** [comment]
I also agree that the time-input shouldn't get in this state for the 12-hour variant. Given the two options in @bjankord's comment, it looks like the second option will not address this issue since that's how it currently works (honoring whatever the variant is set). Sounds like @mmalaker's preference is to go with the first option (to ignore the 12-hour variant if set and use the default 24-hour variant for locales that do not use the 12-hour format).

**Comment by gerard-isdell** [comment]
> The translation team has noted that en-US, es-US, and ar are the only locales from our supported locale list that should include 12 hour display.

Why is that?  Just trying to understand why en-GB, for example, shouldn't include a 12 hour display.

**Comment by bjankord** [comment]
Talked in scrum today with @benbcai and @mmalaker. The consensus was to move forward with putting more weight on locale instead of time format variant. 

If you set the variant to `12-hour` but the app is being rendered in a locale that uses `24-hour` format, the time input will not honor the `12-hour` variant and instead honor the locale indicating that it should use `24-hour`. Essentially, the `12-hour` variant will only work in locales that commonly use `12-hour` formats. (`en-US`, `es-US`)

There is some ambiguity around if `en-GB` should work similar to `en-US` in this regard, or if that locale should always use `24-hour` format. We'll be working with the translation team to find an answer for that.

@gerard-isdell Is 12 hour format common in the UK or is 24-hour format more common?

**Comment by benbcai** [comment]
After discussing with the Terra team, we decided to handle locales that only use the 24-hour format by always displaying the component in the 24-hour variant regardless what the `variant` prop is set to. For locales that use both the 12-hour and 24-hour formats, it will continue to work like it does today by honoring the `variant` prop. 

Currently, if the `variant` prop is set to 12-hour for locales that only use the 24-hour format, consumers are only able to enter a time from 12:00 a.m. to 11:59 a.m. The fix will fall back to the default 24-hour format, which will still allow consumers to enter what ever time they were able to enter with the addition of the time from 12:00 p.m. to 11:59 p.m. For this reason, we do not think this would be a breaking change.

@gerard-isdell According to these references ([1](https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/i_xfdl_r_formats_en_GB.html) and [2](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom)), en-GB does use the 12-hour format. I will reach out to the translation team to figure out which of the currently supported locales do and do not use the 12-hour as this is important for this implementation.

**Comment by benbcai** [comment]
@calebmeyer I believe the issue that you described above about the onBlur is because `2019-04-09` is an excluded date that you either set in the `excludeDates` or `filterDate` props. It is also possible that this date is outside of the `minDate` and `maxDate` range. Hence, once you click on the date input, the date gets cleared because it is an excluded date.

**Comment by benbcai** [comment]
The translations team indicated that the following locales/languages accept and do not accept the 12-hour time notation.

- Do not accept 12-hour time notation. If the `variant` prop is set to `12-hour` for ones of these locales, it will be ignore and defaults to use the `24-hour` variant.
  - `de`
  - `es-ES`
  - `fr-FR`
  - `fr`
  - `nl-BE`
  - `nl`
  - `pt-BR`
  - `pt`
  - `sv-SE`
  - `sv`

- Accept both 12-hour and 24-hour time notations. Honors the `variant` prop as set.
  - `ar`
  - `en-AU`
  - `en-CA`
  - `en-GB` Note: The NHS only accepts the 24-hour notation but the 12-hour notation is still accepted in the UK. Since this component can be consumed in non-clinical/healthcare applications, we should also allow the 12-hour notation.
  - `en-US`
  - `en`
  - `es-US` Note: [reference](https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/i_xfdl_r_formats_es_US.html)
  - `es` Note: Spain uses only 24-hour notation but Mexico and Dominican Republic are examples that use the 12-hour notation.

**Comment by bjankord** [comment]
Nice work on the spike @benbcai, I think this gives us a good path forward for how we should resolve this issue.
