### ISSUE TITLE
Add support for ability to add icons top navigation

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#409]
# Feature Request

## Description
Today we have apps where clients can assign icons to the navigation items.  A request has arisen that we allow for the same to occur in the terra-application-layout top navigation to help ease the migration to the terra-application-layout.

## @ Mentions
@mhemesath @nickpith @neilpfeiffer @tbiethman @alex-bezek  @dkasper-was-taken  @mjhenkes @dev-cprice @JakeLaCombe

**Comment by dev-cprice** [comment]
# Tech Design

## Overview

In order to add icons (with theming) to the existing (soon to be deprecated) `Terra Application Layout`, we need to enhance the `terra-application-links` and `terra-application-layout` packages.

## Example

This was quickly hacked together sans some styling changes:

![image](https://user-images.githubusercontent.com/34115417/54380331-29460880-4659-11e9-83f1-10fbbd54de3d.png)

## Proposed Changes

### Application Layout

The `navigationItems` is [currently](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-layout/src/utils/propTypes.js#L31-L35) a list of objects with the shape:

```js
{
  path: PropTypes.string.isRequired,
  text: PropTypes.string.isRequired,
  hasSubMenu: PropTypes.bool,
}
```

We need to enhance this shape to include an optional `icon` node:

```diff
{
  path: PropTypes.string.isRequired,
  text: PropTypes.string.isRequired,
  hasSubMenu: PropTypes.bool,
+  icon: PropTypes.node,
}
```

The icon needs to be passed down to the `applicationsLinks` prop of the `ApplicationHeader`:

```jsx
<ApplicationHeader
  ...
  applicationLinks={{
    ...
    links: navigationItems ? navigationItems.map((route, index) => ({
      ...
      icon: route.icon,
    })) : undefined
  }}
```

The application layout needs to be able to determine if the config it has been given contains icons and use that knowledge to flex between [standard header height](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-layout/src/header/ApplicationHeader.module.scss#L7)

If there are icons, all primary nav tabs ***should*** have icons, however, to be safe, let's assume that we should flex the size if we have even one tab with an icon, using `.some()`:

```js
const headerHasAnyIcons = (navigationItems || []).some(item => item.icon);
```

The `headerHasAnyIcons` variable can be used as a boolean input to the `ApplicationHeader` to determine which height to use, through typical className selection logic:

```js
// packages/terra-application-layout/src/header/_ApplicationHeader.jsx

const propTypes = {
  ...,
  hasIcons: PropTypes.bool,
};

const defaultProps = {
  ...,
  hasIcons: false,
};

class ApplicationHeader extends Component {
  ...
  render() {
    const {
      ...,
      hasIcons, // defaultProps as false
    } = this.props;

    const headerClassNames = cx([
      'application-navbar',
      { 'application-navbar-with-icons': hasIcons },
      ...
    ]);
  }
}
```

```css
# packages/terra-application-layout/src/header/ApplicationHeader.module.scss
.application-navbar {
  ...
  height: var(--terra-application-layout-navbar-height, 3.5714285714rem); # 50px default
  ...
}

.application-navbar-with-icons {
  height: var(--terra-application-layout-navbar-with-icons-height, 5.142857143rem); # 72px default
  # or reuse the --terra-application-layout-navbar-height
}
```

### Application Links

Similar to the change to the `navigationItems` shape above, the [Application Links Shape](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/ApplicationLinks.js#L4-L26) needs to be enhanced to include an optional `icon` node:

```js
const ApplicationLinksPropType = PropTypes.shape({
  ...,
  links: PropTypes.arrayOf(PropTypes.shape({
    ...,
    icon: PropTypes.node,
  })),
});
```

We need to include the icon node in the [ApplicationTabs](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/ApplicationTabs.jsx) which will pass down the icon to each rendered tab, through the [tab props](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/ApplicationTabs.jsx#L154-L162):

```jsx
links.forEach((link, index) => {
  const tabProps = {
    ...,
    icon: link.icon,
  };
  ...
});
```

The [_Tab.jsx file](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/_Tab.jsx) will be where the icon consumption occurs:

```jsx
class ApplicationTab extends Component {
  render() {
    const {
      ...,
      icon,
    } = this.props;

    ...

    return (
      <ComponentClass ...>
        <div className=cx(['tab-inner'])> // change to flex-direction: column
          <span className={cx(['tab-icon'])}>{icon}</span>
          <span className={cx(['tab-label'])}>{text}</span>
        </div>
      </ComponentClass>
    );
  }
}
```

Of course, theming and styling can be enhanced and included in the [ApplicationTabs.module.scss](https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/ApplicationTabs.module.scss)

cc @alex-bezek @mhemesath @bjankord

**Comment by bjankord** [comment]
This design looks good to me.  I'd recommend going forward with:
```
.application-navbar-with-icons {
  height: var(--terra-application-layout-navbar-with-icons-height, 5.142857143rem); # 72px default
}
```
instead of reusing `--terra-application-layout-navbar-height` here.

I'd also recommend splitting the rendering of the tab into 2 versions based on the `hasIcon` prop. The first version should maintain it's current rendering for passivity. The second rendering, based on `hasIcon` being true can be fore the changes needed to render the icon.

**Comment by mhemesath** [comment]
Seems good to me, are we going to allow icon spacing within the rollup menu?

**Comment by JakeLaCombe** [comment]
Nice job! I approve of this idea. +1 from me

**Comment by tbiethman** [comment]
Are you wanting the icons to also render in the toggle-able menu in small viewports?
