### ISSUE TITLE
Flex Date, Time and DateTime controls according to the container

### ISSUE THREAD

**Issue by Nahusha-MS** [cerner/terra-framework#462]
# Feature Request

## Description

Currently, the controls are of fixed width and do not adjust to the container. If the container width is large, the controls look very small. 
## Additional Context / Screenshots

Without wrapping : 
<img width="1440" alt="screen shot 2018-07-23 at 10 13 57 pm" src="https://user-images.githubusercontent.com/41947815/43656349-c369e18c-976f-11e8-8558-7e109ef54151.png">
With wrapping : 
<img width="1440" alt="screen shot 2018-07-23 at 10 08 58 pm" src="https://user-images.githubusercontent.com/41947815/43656400-e7228764-976f-11e8-98a9-5ed9eb1ec1b4.png">

**Comment by at014421** [comment]
Any update on this @neilpfeiffer?

**Comment by bjankord** [comment]
Noticed this with updates to date time picker when the seconds input is displayed. 
It looks like it is complete cut off on mobile.

<img width="385" alt="Screen Shot 2019-07-02 at 1 59 26 PM" src="https://user-images.githubusercontent.com/633148/60540454-d0b47d00-9cd4-11e9-9432-65a0414de042.png">

**Comment by neilpfeiffer** [comment]
Closing as Not Supportable by Terra.

Two items prevent Terra from being able to support this request for date-picker, time-input, and date-time-picker, allowing it to match the styling of other basic text inputs and form elements like the images above: 

----
1. Cerner Design Standards for [Input Fields](https://wiki.cerner.com/x/MFcVYQ#InputFields-Bestpractices) currently calls out that specific input fields are sized specifically to the content being entered, time and dates included:
> Input fields should be sized appropriately for the content the user may enter.  There are three input field lengths: 
• Fixed: These input fields are a set character length because the entered content is always the same length. Examples: Phone number, credit card, dates

Which means that for the current implemented design, Date and Time inputs have limited flexibility and not permitted able to stretch to fit their container or grid, similar to how the other form inputs can. New designs would be needed to be able to best follow the Design Standard guidance while also working as a full unit for your collection of advanced clinical form components.

----
2. The Date-Time-Picker has four internal elements, two fixed (the date input and the time input) and two variable (AM/PM selector and Ambiguous Hour Indicator for Daylight Savings Time), and the layout options for the current design requires it to wrap as the primary responsive pattern when there is not enough horizontal space available: 
![image](https://user-images.githubusercontent.com/1355485/81981808-6d82bf00-95f6-11ea-88b5-ad9ff25e7c34.png)
. ![image](https://user-images.githubusercontent.com/1355485/81981820-72e00980-95f6-11ea-81c6-4087e5d057e1.png)

It is not possible to constrain all 4 items to always present on one line for all widths, or have them wrap and have each item stretch their widths to fit a grid/column, with a manner that easily makes them fit your current pattern allowing the additional comment indicator to be added on the end of the input grouping. In order to do properly, a new component layout construction would be needed to best handle all the internal items, with an intentional design that allows it to fit into a flexible width grid system (and meet Design Standards).

----
Recommendation from the Terra group is two parts: 
- _immediate term:_ work with Nick Kroeker and Justin Eddings to determine any appropriate design adjustments within your project to best account for these three Terra inputs not being able to flex the presentation beyond how they currently function.
- _long term:_ due to the fact that these advanced/complex form constructions take basic Terra form elements and add-on a great deal of functionality and additional user interface, it is our suggestion that these become new first-class, independent suite of clinical-specific form components that do not rely-on and import the basic terra-form elements, such that they can be fully tailored to suit their purpose, fit well within fluid grids, be appropriately responsive and accessible, and are not bound by the same restrictions that our current date and time pickers have. UX will need to revisit the design options in order to accomplish making new components. 

cc: @Nahusha-MS @at014421
