### ISSUE TITLE
Update version of react-datepicker used in terra-date-picker

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#465]
# Feature Request

## Description
New major version of react-datepicker is available. We should look into updating this dependency.

**Comment by benbcai** [comment]
react-datepicker v2.0 removed the dependency on moment in favor of the native Date object. The new major version now uses [date-fns](https://github.com/date-fns/date-fns) for any date and time manipulations. 

These are the issues we have encountered thus far in v2.0 and using date-fns.
- [These](https://github.com/date-fns/date-fns/tree/master/src/locale) are the locales that date-fns currently supports. These are the ones we need that it doesn't currently support: `ar`; `en-AU`; `es-ES`; `es-US`; `fr-FR`; `nl-BE`; `sv-SE`. Although, it does support some of these locales, it does support their language. Without these locales, the months and days of week in the calendar will not be translated.
- date-fns doesn't have a mature [time-zone](https://github.com/date-fns/date-fns/blob/master/docs/timeZones.md) library. [date-fns-tz](https://github.com/marnusw/date-fns-tz) and [date-fns-timezone](https://github.com/prantlf/date-fns-timezone) are two available libraries but currently they are at their early stage. 
- The parse function in date-fns doesn't do [strict parsing](https://github.com/date-fns/date-fns/issues/942). See issue [#1655](https://github.com/Hacker0x01/react-datepicker/issues/1655)

**Comment by RHolland13** [comment]
[This comment](https://github.com/cerner/terra-framework/issues/465#issuecomment-445324602) makes it sound as if we’d actually prefer to use AirBnB’s library, but consider the inclusion of Moment to be a deal-breaker.  Is Moment really that bad that moving away from it is more desirable than moving to what sounds like is otherwise considered to be a better datepicker?  What do we expect to gain by moving away from Moment?  Is it just bundle size? 
In my opinion, AirBnB’s stance on Moment is actually an advantage of their library.  It seems like they intend to continue using a reliable and popular option until the official browser API is finalized and a decent polyfill implementation for that is available.  I think I agree with them.
My understanding is that a lot of Moment’s size comes from it supporting internationalizations for more locales, and from including the tz database.  It looks like it is possible to remove locales that you don’t want to support, reducing Moment’s bundle size.  Additionally, properly supporting IE requires including the tz database, as [IE lacks proper support for historical DST transitions]( https://gist.github.com/RHolland13/a29679a95edd8e01b6b14ca9b5041ffb).  So (as @benbcai has mentioned), we’d need to include an additional piece for that.  It’s still entirely possible that Moment is bigger even after accounting for those things, but I think an apples-to-apples comparison would reduce the difference.
Removing Moment over bundle size concerns would force everyone consuming this package to also migrate from Moment to whatever solution is chosen here, or else the bundle size gains can’t be realized, and in fact downstream bundle sizes would be increased, as they’d now have date-fns in addition to Moment.

**Comment by bjankord** [comment]
We've been considering what path we want to move forward with for the date picker. There is a slew of [date picker](https://github.com/cerner/terra-framework/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adatepicker+) / [date time picker](https://github.com/cerner/terra-framework/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22date+time+picker%22+) issues that have been logged. Having someone familiar with the problem space like yourself Robert would be really helpful to work through those issues.

@JakeLaCombe has done an evaluation of migrating to airbnb's react-dates. I'll ask him post his results here. 

Ben has been exploring updating the current third-party date picker we use. 

There is [a related terra date time picker issue](https://github.com/cerner/terra-framework/issues/454) from a team noting large bundle sizes when pulling in terra-date-time-picker. 

The main benefit of moving away from MomentJS that I see would be reduced bundle size.

These are some good points you bring up @RHolland13 👍
Let's keep the conversation going and see if we can find some resolution to these issues.

**Comment by JakeLaCombe** [comment]
So I evaluated react-dates, and found the module unusuable for our purposes.

- Containers have to have overflow: hidden as the date picker is not portaled by default.
- No auto detection of opening up and down based on available space.
- No popper integration. We would have to implement our own logic to determine if the date picker should open on the top or the bottom potentially. If there is not enough room, the document adds more space.
- Colors are theme able, but it’s recommended to do all the margins and sizes through the JavaScript
- OnChangeRaw is not available as a prop, and can not be passed to the date picker.
- No custom input attributes

**Comment by bjankord** [comment]
Talked with the other terra maintainers today about the points you brought up @RHolland13. We landed on consensus around continuing to use MomentJS. We'll have some more talks with the terra team as a whole tomorrow. Following that we'll log a new issue describing the direction we're planning to take for the terra date picker and related issues logged against it.

**Comment by bjankord** [comment]
We're planning to create a fork of [Hacker0x01/react-datepicker v1.8.0](https://github.com/Hacker0x01/react-datepicker/releases/tag/v1.8.0) within the terra-date-picker package. This is the last version that used MomentJS. Per @RHolland13's comments we see the value of continuing to use MomentJS and the issues that would come up if we move away from it.

**Comment by bjankord** [comment]
Closing this issue as it is no longer necessary.
