### ISSUE TITLE
[terra-tabs] Allow additional tabs to be added after initial mount of Tabs component

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#486]
# Issue Description

The Tabs component has some internal state that manages the visible tab panes. If additional panes are added after the initial mounting, that state is not updated and the added panes are not visible. 

We should make changes to ensure that componentWillReceiveProps is implemented and keeping the internal component state in sync with the props.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by nramamurth** [comment]
**Initial Investigation -**

Here's the sample that I have been testing on ⬇️

```
import React from 'react';
import Tabs from 'terra-tabs';

class VisibleTabsTest extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      tabKeys: [...Array(5).keys()],
    };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        tabKeys: [...Array(8).keys()],
      });
    }, 5000);
  }

  createTabPanes() {
    const tabPanes = this.state.tabKeys.map((tabKey) => (
      <Tabs.Pane label={`Tab ${tabKey}`} key={tabKey} id={tabKey}>
        <div>
          {`Tab ${tabKey}`}
        </div>
      </Tabs.Pane>
    ));

    return tabPanes;
  }

  render() {
    return (
      <Tabs id="visibleTabsTest">
        {this.createTabPanes()}
      </Tabs>
    );
  }
}

export default VisibleTabsTest;
```

This is an issue _only_ with [CollapsibleTabs](https://github.com/cerner/terra-framework/blob/master/packages/terra-tabs/src/_CollapsibleTabs.jsx). The tabs that we show and the ones we do not show [depend on an index (`hiddenStartIndex `) that we maintain](https://github.com/cerner/terra-framework/blob/1613dd8dcdbdd7c85a5ebda9e4d463b2e7ad9d48/packages/terra-tabs/src/_CollapsibleTabs.jsx#L250-L256) — this index is being [set upon resize](https://github.com/cerner/terra-framework/blob/master/packages/terra-tabs/src/_CollapsibleTabs.jsx#L148) which is handled multiple times in multiple scenarios. However, upon component update due to more children now (read: more tabs added), the control currently _never_ [hits the resize handler and instead hits the else block in `componentDidUpdate`](https://github.com/cerner/terra-framework/blob/1613dd8dcdbdd7c85a5ebda9e4d463b2e7ad9d48/packages/terra-tabs/src/_CollapsibleTabs.jsx#L76-L83) and nothing happens (new tabs are not seen because `hiddenStartIndex` is not updated because the resize handler is not invoked).

**Comment by nramamurth** [comment]
@tbiethman @dkasper-was-taken 

I wonder why `_CollapsibleTabs` does not maintain its own internal state but looking at the current code as-is, I think all that we need to do is reset the "cache" when the component updates —

```diff

componentDidUpdate(prevProps) {
    if (this.isCalculating) {
      this.isCalculating = false;
      this.handleResize(this.contentWidth);
+    } else if (React.Children.count(this.props.children) !== React.Children.count(prevProps.children)) {
+      this.resetCache();
+      this.forceUpdate();
     } else {
      this.handleSelectionAnimation();
    }
 }

```

I have a draft PR out to get a deployment out - it'd be great if you could check it out and let me know if there's something more that I need to handle. 

Also, is this technically a "bug"?

**Comment by tbiethman** [comment]
* I think your change is sufficient.
* Unless there's documentation stating the existing limitations, I'd consider this a bug.
* isCalculating is set when the tab widths are being calculated. It is used to visibly hide the tabs during calculations (it's pretty flashy otherwise).
