### ISSUE TITLE
DateTime Picker needs more of the props exposed

### ISSUE THREAD

**Issue by PandaFlieg** [cerner/terra-framework#497]
# Feature Request

## Description
As a consumer, I want a lot of the internal state available so that I dont need to recalculate and duplicate the logic done inside the separate controls.  

This includes:
- When the control is in the ambiguous hour
- When the date control is empty
- When the date control is invalid
- When the time control is empty (potentially to the granularity of both the hour and minute controls)
- When the time control is invalid (potentially to the granularity of both the hour and minute controls)

## Additional Context / Screenshots
We are needing a date time component where the control has to be filled out and has to be valid.  While we can default the value, and we are, a user could remove said value and depending on how much information is filled out, we may not be able to delineate between '00:00' and an empty value.  

As for the ambiguity check, our use case is we have 2 timezones that we manage.  If these two timezones diverge, we put a timezone abbreviation of one of the timezones to the right of this control.  The issue arises when this control is ambiguous, it also puts a timezone abbreviation to the right of the control.  We need to be able to suppress our timezone abbreviation if the date time control is showing it's abbreviation.

**Comment by ryanthemanuel** [comment]
@PandaFlieg would listening to the onBlur event described here (https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/events) help you with the last 4 items in your bullet?  As for the ambiguous hour, would it be helpful if we had a new prop that allowed for the time zone to always display?

**Comment by benbcai** [comment]
> When the control is in the ambiguous hour

Currently, there is no API to indicate that the entered time is the ambiguous hour but we can easily return a flag in onChange/onChangeRaw to do so. 

> When the date control is empty
When the date control is invalid
When the time control is empty (potentially to the granularity of both the hour and minute controls)
When the time control is invalid (potentially to the granularity of both the hour and minute controls)

You can listen to onChange/onChangeRaw or the [options](https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/events) returned in onBlur depending on when you need to handle this.

**Comment by benbcai** [comment]
@PandaFlieg When during the workflow do you expect this information to be sent to the consumer? Do you expect this to be sent as soon as the change is made (i.e. OnChange/OnChangeRaw) or when the focus leaves the entire container component (i.e. OnBlur).

**Comment by PandaFlieg** [comment]
Our requirements have changed a bit since this was first posted but after reading the api here:
https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/events
for onBlur, I am thinking there is a chance we could subscribe to the onBlur event for the validation we need.

The only exception to this rule might be for the ambiguous hour mentioned in the first post.

I'll see if I can get an update on the requirements we need as we had re-prioritized the controls we supported based on what implementations were available.

**Comment by benbcai** [comment]
## Design

### terra-date-time-picker
- The [onBlur](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-time-picker/src/DateTimePicker.jsx#L314-L319) callback currently provides some [metadata](https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/events) about the state of the entered date/time value. We should extend this to include the following information:

  - `isAmbiguousHour` - Use the [checkAmbiguousTime](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-time-picker/src/DateTimeUtils.js#L139-L157) helper to determine if the entered date/time is ambiguous. We could add a new `onAmbiguousHour` callback prop to notify the consumer but adding this as an attribute in the metadata make it more consistent with the existing data.
  - `dateValue` and `timeValue` - The current metadata returns and `inputValue` string that includes both the date and time values. With the date and time values separated out, this makes it easier for consumers read and parse to determine if each value is empty/invalid.

- Currently this metadata is only returned in `onBlur`, we should wrap this [logic](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-time-picker/src/DateTimePicker.jsx#L278-L319) in a function and return the same metadata for the `onChange` and onChangeRaw` props. Note: The [onChange](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-time-picker/src/DateTimePicker.jsx#L438) and [onChangeRaw](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-time-picker/src/DateTimePicker.jsx#L385) props currently already return the entered value as the second parameter. For passivity, the additional metadata should be added in a third parameter instead of consolidating them.

### terra-date-picker
- The additional attributes above are not applicable to the date-picker. However, the existing [metadata](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-picker/src/DatePicker.jsx#L247-L252) returned in `onBlur` should also be returned on [onChange](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-picker/src/DatePicker.jsx#L271) and [onChangeRaw](https://github.com/cerner/terra-framework/blob/6e14a207572bc52b859eb4d1efe2da5037cf0054/packages/terra-date-picker/src/DatePicker.jsx#L279) for consistency with date-time-picker.


### terra-time-input
- terra-time-input currently just returns the entered time value and doesn't return the additional metadata like in date-time-picker. However, since those additional metadata in date-time-picker are not applicable for the time-input, the returned time value should be sufficient to consumers to validate and make decisions.


cc/ @PandaFlieg

**Comment by PandaFlieg** [comment]
@benbcai talking over our requirements and how they've changed, I'm thinking this should be sufficient for what we need.

**Comment by ShettyAkarsh** [comment]
@benbcai ,should we pass any parameters here for onAmbiguousHour callback ? if No, then Should AmbiguousHour check be a boolean attribute or callback ?  anyhow dateValue, timeValue and inputValue provides the required data to the consumers.

**Comment by benbcai** [comment]
@ShettyAkarsh I don't think we need the `onAmbiguousHour` callback prop since we will add the `isAmbiguousHour` in the metadata returned in the `onBlur`, `onChange`, and `onChangeRaw` props. `isAmbiguousHour` should be a boolean. 

@PandaFlieg Does returning the `isAmbiguousHour` boolean in the `onBlur`, `onChange`, and `onChangeRaw` props sufficient for your use case to determine whether or not to suppress your version of the timezone abbreviation? Or is there a need for this to be a callback prop instead of a boolean attribute?
