### ISSUE TITLE
[terra-date-picker] expose onFocus method

### ISSUE THREAD

**Issue by SharathAlur** [cerner/terra-framework#498]
# Feature Request
Expose onFocus method

## Description
onFocus method is required to focus on the control programatically.

Since onFocus is not there, we can not use the auto-focus on error functionality in react-final-form.

**Comment by benbcai** [comment]
@SharathAlur We delete the onFocus prop [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/DateInput.jsx#L144-L146) because we do not want the calendar picker to automatically display when the input receives focus. You can pass in a handler to the `onInputFocus` prop in DatePicker to see if that works for you. We should make `onInputFocus` a first class prop so that consumers are aware of it. I'll leave this issue open to make this change.

**Comment by JakeLaCombe** [comment]
What goal are you looking to achieve with this issue? Perhaps there is something else we can do to resolve it?
