### ISSUE TITLE
Failed propType warning for terra-date-picker using selectedDate prop

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-framework#528]
# Bug Report

## Description
terra-date-picker throws a console warning when rendering with the selectedDate prop filled out as a string.  That string is then given to the underlying react-datepicker component that expects it to be a date.

API for terra-date-picker showing that the selectedDate prop is a string:
https://engineering.cerner.com/terra-ui/#/components/terra-date-picker/date-picker/date-picker

API for the react-datepicker component that expect it to be a date:
https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#L134

## Steps to Reproduce
1.  Render the terra-date-picker and give it a selectedDate prop on initial render

## Additional Context / Screenshots
<img width="437" alt="screen shot 2019-02-18 at 4 41 04 pm 1" src="https://user-images.githubusercontent.com/1711642/53429864-0ce87180-39b3-11e9-9910-3243d6783da6.png">

## Expected Behavior
No warning to be shown in the console

## Possible Solution
Convert the string to a date object before giving it to react-datepicker

**Comment by benbcai** [comment]
@kschuste For the `selectedDate` prop, are you either passing in an empty string (``), an invalid ISO8601 date or a valid ISO8601 string but it is outside of the `minDate` and `maxDate` range? The `selectedDate` prop is converted to a moment object [here](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L111) before sending down to react-datepicker. But if you pass in an empty string or it can't be converted, this [helper](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/DateUtil.js#L12) would just return the original string. I think it should return `undefined` instead of the original value in these cases to prevent this.state.selectedDate from being passed down as a string.

**Comment by kschuste** [comment]
@benbcai we were passing in an empty string into the DatePicker.  Passing in undefined over an empty string does solve the warning that we are getting.  As a consumer, I would expect to be able to use an empty string as nothing the same as undefined.
