### ISSUE TITLE
Application Header components not aligned

### ISSUE THREAD

**Issue by SushmithaBN** [cerner/terra-framework#593]
# Bug Report

## Description
The application header contains user information on the right-top corner.
In chrome and IE11 other newer browsers, the title shows properly, but it gets aligned beside the Application layout title.

## Steps to Reproduce

1. Load [terra-application-layout](https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/about) in a new browser (Chrome, IE 11, etc.)
2. Remove the navigation items by making it null or empty array.
3. It can be observed that the user name information come to left (gets aligned beside the Application layout title.)

## Additional Context / Screenshots
**Chrome**:
![image](https://user-images.githubusercontent.com/42537313/55605692-4f138880-5793-11e9-8e23-9a0589297eb1.png)

**IE11**:
![image](https://user-images.githubusercontent.com/42537313/55605736-78341900-5793-11e9-8061-a29cbc3a2fc3.png)
## Expected Behavior
User name should get right-aligned
![image](https://user-images.githubusercontent.com/42537313/55605816-d9f48300-5793-11e9-87d3-f8bafc40fbe6.png)

## Environment

* Component Name and Version: terra-application-header-layout@4.8.0
* Browser Name and Version: Chrome, IE 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version: 3.2.0
* Operating System and version (desktop or mobile): MAC and Windows 10

**Comment by nramamurth** [comment]
@SushmithaBN How are you creating the `ApplicationHeaderLayout` in your project? A sample of how you are defining the `ApplicationLayout` using 'the user information' will be helpful, me thinks.

**Comment by nramamurth** [comment]
I noticed that irregardless of the fix that went in as part of https://github.com/cerner/terra-framework/pull/554, the `Utilities` is positioned to the left when `ApplicationHeaderLayout` is created **_just_** with `utilities`. 

```
  <ApplicationHeaderLayout
     id="test-header"
     utilities={<div id="test-utilities">Utilities&nbsp;</div>}
  />
```

**Example:**

![Screen Shot 2019-04-05 at 12 44 47 PM](https://user-images.githubusercontent.com/10090859/55610509-b6840500-57a0-11e9-82b9-60e244ab73a2.png)

This makes me wonder (I could be wrong) if the header should have a `header-inner` block element created irrespective of whether or not there is any navigation item or an extensions item so that the styles for each individual sub-component fall into place.

https://github.com/cerner/terra-framework/blob/3fad053c954f0175ca8d1a3e3d1d661a1e2ff51f/packages/terra-application-header-layout/src/ApplicationHeaderLayout.jsx#L77-L84

@neilpfeiffer @bjankord What are your thoughts?

**Comment by nramamurth** [comment]
@neilpfeiffer @bjankord Any word on this one?

**Comment by bjankord** [comment]
@nramamurth You're [proposal](https://github.com/cerner/terra-framework/issues/593#issuecomment-480174542) sounds good to me 👍

**Comment by nramamurth** [comment]
I tested it on IE as well and I did not really see an issue. @neilpfeiffer what are your thoughts about having `header-inner` all the time?

**Comment by tbiethman** [comment]
+1 sounds like a good fix to me
