### ISSUE TITLE
Default browser focusing style adds blue line wrapping slide panel

### ISSUE THREAD

**Issue by FloraChenCerner** [cerner/terra-framework#609]
# Bug Report

## Description

#584 set the detailed panel to be focused when slide panel is open. With this change the browser's default focusing style adds a blue line on the left of detail panel, and when dismissing the detail view, master view is wrapped with blue outline. This behavior fails most of our components wdio tests, and we don't want the blue line from the UX perspective. 

One of the failing build jobs: https://jenkins.cerner.com/ion/job/ion-chart/job/ion-conditions-js/job/master/159/

## Steps to Reproduce

1. Implement a slide panel with any behavior. 
2. Open the slide panel and see the blue outline around detail panel
3. Close the slide panel and see the blue outline around master panel

## Additional Context / Screenshots

![1128283 _Renders_Detail_on_Condition_Selection default 1300x768](https://user-images.githubusercontent.com/43655107/56145845-b0ddaa80-5f6a-11e9-9066-96ef962cb71f.png)

## Expected Behavior

No blue outline around master or detail panel when opening/closing

## Possible Solution

Probably to make the style of focusing to be clear

## Environment

* Component Name and Version: terra-slide-panel 3.3.0
* Browser Name and Version: Chrome Version 73.0.3683.10
* Operating System and version (desktop or mobile): Mac OS

## @ Mentions

@dkasper-was-taken @tbiethman

**Comment by tbiethman** [comment]
We'd just need to set `outline` to `none` for the two SlidePanel content areas that are now focusable.

**Comment by neilpfeiffer** [comment]
As long as the element that receives the focus when the panel gets the focus-trap is the parent container and not an actionable element (and the parent container could/should never have actionability on it, it would be the similar as the when the base body technically has the focus before user clicks tab for the first time) -- lets go ahead and add the outline:none, since there is a clear and obvious visual interaction of the panel opening which is the same effect as a visual indication of focus location.
