### ISSUE TITLE
slidepanel's dom ordering  flexing based on prop

### ISSUE THREAD

**Issue by chriskonopka** [cerner/terra-framework#647]
# Feature Request

## Description

requesting that the slidepanel's dom ordering is flexed when the start vs end panelPosition prop is updated. This would allow a developer to control the tab order of the slide panel component. Currently it is impossible to have the side panel's contents take tab precedence over the main  

## @ Mentions

@dkasper-was-taken  talked to me over teams about this

**Comment by supreethmr** [comment]
this can be done by changing the Dom order of [Panel content](https://github.com/cerner/terra-framework/blob/ab093a9a2203d5f4a90fe3aaa66e18c719328e02/packages/terra-slide-panel/src/SlidePanel.jsx#L107) and [Main content](https://github.com/cerner/terra-framework/blob/ab093a9a2203d5f4a90fe3aaa66e18c719328e02/packages/terra-slide-panel/src/SlidePanel.jsx#L104) based on panel position. 

Since focus flows in the order elements specified in dom, In order to have focus on panel content when panel position is set to start panelContent should be placed before mainContent. So that panel content receives focus before main content. 

Exiting Code : mainContent is followed by panelContent for both panel positions start and end like shown below 
```
  <div className={cx('main')} tabIndex="-1" ref={this.mainNode}>
    {mainContent}
  </div>
  <div className={cx(['panel'])} tabIndex="-1" aria-hidden={!isOpen ? 'true' : 'false'} ref={this.setPanelNode}>
    {panelContent}
  </div>
```

**Possible Fix :** 
 Check if panelPosition is set to start then place panelContent above the mainContent like below : 
```
 const content =(panelPosition === 'start') ? (
   <React.Fragment>
     <div className={cx(['panel'])} tabIndex="-1" aria-hidden={!isOpen ? 'true' : 'false'} ref={this.setPanelNode}>
       {panelContent}
     </div>
     <div className={cx('main')} tabIndex="-1" ref={this.mainNode}>
       {mainContent}
     </div>
   </React.Fragment>
    ) : (
   <React.Fragment>
     <div className={cx('main')} tabIndex="-1" ref={this.mainNode}>
       {mainContent}
     </div>
     <div className={cx(['panel'])} tabIndex="-1" aria-hidden={!isOpen ? 'true' : 'false'} ref={this.setPanelNode}>
       {panelContent}
     </div>
   </React.Fragment>
 );
```
else mainContent should be placed above the panelContent and content should be passed to main div like below : 
```
       <div
        {...customProps}
        className={slidePanelClassNames}
        data-slide-panel-panel-behavior={panelBehavior}
        data-slide-panel-panel-position={panelPosition}
        data-slide-panel-panel-size={panelSize}
      >
         {content}
      </div>
```
