### ISSUE TITLE
Remove inline styles in dev site components

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-framework#657]
# Feature Request

## Description

We want to remove inline styles from our dev site components to set a better example for consumers of terra.  As a replacement, we should pass in classes and use css to style the components.

**Comment by avinashg1994** [comment]
While running the lint checks for terra-framework, i see that there are warnings indicating for inline styles in the "src" or "main" file as well, like for "_PopupContent.jsx" in the **Popup** package.
So do we have to make changes there as well, since the issue description says only for "dev-site components".

**Comment by StephenEsser** [comment]
For this issue I think we should stick to updating the dev-site examples only. We'll need to take a closer look at the src files using inline styles on a separate issue.
