### ISSUE TITLE
[terra-popup] Popup does not resize after a scroll bar is rendered

### ISSUE THREAD

**Issue by gabeparra01** [cerner/terra-framework#763]
# Bug Report

## Description
This issue concerns the automatic height feature of terra-popup. The component stops resizing when it becomes large enough to require a scroll bar. The popup will resize correctly as long as it remains small enough to not require a scroll bar.

Here is a gif of the error happening in the ion-condition-js project's stage vanity URL: 
[Popup Does Not Resize.gif.zip](https://github.com/cerner/terra-framework/files/3347012/Popup.Does.Not.Resize.gif.zip)

Here is a gif ot the popup resizing correctly because it never becomes large enough to require a scroll bar:
[Popup Resizes Correctly.gif.zip](https://github.com/cerner/terra-framework/files/3347034/Popup.Resizes.Correctly.gif.zip)

Vanity URL: https://ion-conditions.test.stagingcernerpowerchart.com/v2/patients/2276019/conditions-summary?encounterId=2111957

Github links:
Popup location-https://github.cerner.com/ion-chart/ion-conditions-js/blob/master/src/conditions/components/condition-add/ConditionAddContainer.jsx
isHeightBounded location-  https://github.cerner.com/ion-chart/ion-conditions-js/blob/master/src/conditions/components/condition-add/SearchView.jsx#L314

## Steps to Reproduce
1. Login to the vanity URL.
2. Search for a patient with an encounter
3. Select patient from result list. Select encounter.
4. If prompted for patient-person relationship, choose attending physician
5. Click on the "+" button in the top right hand corner.
6. Type in text that will return a large amount of results. Example: "arm"
7. Delete search text. The popup will remain full screen height and will not resize

## Additional Context / Screenshots
I am working on a project with a similar design and I am seeing the same issue. I tried adding a conditional to set height to auto if isHeightBounded is false. But it hasn't fixed the issue: https://github.cerner.com/procedures/procedures-js/blob/PROCEDURES-453/src/procedures/components/procedure-add/SearchView.jsx#L143

## Expected Behavior
The popup is expected to shrink or grow when new search results are returned

## Possible Solution
I cannot think of a good alternative solution. Trying to force a rerender after receiving a certain number of search results would probably cause performance issues

## Environment

* Component Name and Version: terra-popup. The error happens for both version "^5.2.0" and version "^6.3.0"
* Browser Name and Version: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* Node/npm Version: Node 8/npm 6
* Webpack Version:
* Operating System and version (desktop or mobile): macOS

**Comment by gabeparra01** [comment]
This issue can also be recreated using the dev-site of the other project that I mentioned (procedures-js).
1) npm start
2) Navigate to http://localhost:8080/#/components/procedures-js/procedures-summary
3) Type in "arm" to get a large amount of results that will cause a scroll bar to be rendered.
4) Type in "amp" to get a list of just a few search results

**Comment by gabeparra01** [comment]
@ryanthemanuel We are still seeing this issue. Do you have any ideas for a possible solution?

**Comment by dkasper-was-taken** [comment]
The core problem lies with the terra-popup being unable to determine if the child element updated internal state. It can determine if the container it wraps around the content resizes, but is unable to do so when it's height is bound by the window as it's forced to lock its height in order to allow for fixed headers using flexbox (flexbox having limitations with cross browser support) .

There are two methods to resolve your issue, but both involves additional renders. Though before I go into them, it'd be worthwhile to consider whether or not it needs to have a dynamic height, and could instead be treated more like a fixed height dialog.

The first and easiest is to pull the state of search results out of the popup content, move it to the HOC presenting the popup using callbacks. Your input field returns the search field value, and your HOC passes the results to display backdown as props. That way when the results update the popup will know to lay itself out again, and it will be in sync with results render.

The second and not my favorite, so I don't really recommend it, either add a resizeObserver or an internal callback from the content to tell the HOC to forceUpdate/setState in order to trigger another popup render. It'd work, and keep the logic contained to the popup content, but potentially result in multiple renders, which is it's own can of worms.

**Comment by gabeparra01** [comment]
@dkasper-was-taken Thanks for the advice! I will give the first method a try and let you know if I have any questions. If I am able to get a working solution using the first method, I will post it to this issue

**Comment by ryanthemanuel** [comment]
@gabeparra01, any update on this?

**Comment by gabeparra01** [comment]
@ryanthemanuel I am still working on it

**Comment by gabeparra01** [comment]
@dkasper-was-taken The first method you suggested fixed the issue: 
[Resize After Scroll.gif.zip](https://github.com/cerner/terra-framework/files/3436902/Resize.After.Scroll.gif.zip)
PR: https://github.cerner.com/procedures/procedures-js/pull/61

I only ran into one major issue. The updated results would not be sent to the HOC presenting the popup if the search text was under the 2 character minimum for our searchfield requirements. The workaround I used was using the onChange() prop when rendering the searchfield instead of onSearch(). The application still has logic in place to only show search results when the search text is 2 characters or more.

The only other work around I could think of would be to add state to the HOC component to track the value of the search text. That would make the workflow a lot more complicated because the actual terra-search-field component is a child of the HOC's child.

Thanks again for the help!
