### ISSUE TITLE
[terra-layout] Shim for `<main>` tag is executed too late

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-framework#780]
# Bug Report
 
## Description

The `<main>` tag used by the layout is not officially supported by older IE browsers. We get around that by adding some logic here: https://github.com/cerner/terra-framework/blob/master/packages/terra-layout/src/_LayoutSlidePanel.jsx#L68

However, it seems as though executing this logic within componentDidMount is too late, as a warning still persists when using the terra-layout in IE10 (with React in development mode).

This isn't a functional problem, but it is annoying to see it in the console. 

## Steps to Reproduce

1. Start terra-framework's dev site in development mode
2. Load the site in IE10.
3. See warning in the console.

## Expected Behavior

No warning should be thrown for the `<main>` tag while running the dev build of React.

## Possible Solution

We can instead execute that logic inside the class constructor or before the class is defined. This will ensure that it's executed before the first render and (I hope) suppress the warning.

## Environment

* Component Name and Version: terra-layout
* Browser Name and Version: IE10

**Comment by avinashg1994** [comment]
I tried to execute that logic inside the class constructor as well as before the class, but both these attempts were unsuccessful.
Also i did a quick search and found threads with possible solutions/workarounds, such as adding `role="main"` to the tag or add the style `display:block` and saw that they were already implemented and the warning still persists.
@tbiethman , your thoughts on this or possible alternatives?

**Comment by tbiethman** [comment]
Well shoot, I thought that'd help, but I guess not. This is the logic to see whether that warning is logged: https://github.com/facebook/react/blob/67e3f3fb6e342f95f00215c84d5d013d7b0e1b33/packages/react-dom/src/client/ReactDOMComponent.js#L462

I'd throw a breakpoint there to see if there's a realistic way to get that check to fail. If not, we might just have to live with the warning. 🤷‍♂

**Comment by avinashg1994** [comment]
Well, I spent sometime investigating this and was not able to break the condition here: https://github.com/facebook/react/blob/67e3f3fb6e342f95f00215c84d5d013d7b0e1b33/packages/react-dom/src/client/ReactDOMComponent.js#L462.

But i did find a workaround which works, but i am skeptical about the approach:
As seen in this conversation https://stackoverflow.com/questions/55010078/main-tag-is-unrecognized-in-ie11-react-application, by overriding the `console.error` method and filtering the message, if the error pattern matches with the specified one.

I feel that we could just mark this issue as "won't fix", Since it is just an issue with IE and that to only in development mode. Also it does not hamper with the functionality and is just a console warning.
@tbiethman, your thoughts on this?

**Comment by bjankord** [comment]
Talked with @tbiethman and @ryanthemanuel about this. I believe we are going to consider this a bug with React and mark it as `won't fix`. It doesn't appear to affect the rendering of the `<main />` element in IE.
