### ISSUE TITLE
[terrra-appilcation-naivation] No check for presence of utils

### ISSUE THREAD

**Issue by dkasper-was-taken** [cerner/terra-framework#829]
# Bug Report
No check for empty utilities

## Description
While rare, if no utilities and no settings/help/logout are provided to terra-application-navigation we still show the utility button, that should not be displayed.

## Possible Solution
In the header implementation check for the length of utils and the presence of settings/help/logout, and if nothing exists do not render the utility button.

## @ Mentions
@tbiethman

**Comment by avinashg1994** [comment]
Besides checking for length of utils, presence of settings/help/logout, do we also have to check for the presence of "hero" and "userConfig" as well?

1. In the following scenario do we check for the presence of "hero", since it is the only content in the Utilities?
<img width="960" alt="hero" src="https://user-images.githubusercontent.com/50138162/63350091-65089b00-c37a-11e9-8e5b-17b898ac826c.png">

2. A similar scenario here as well, when "userConfig" is the only item in the utilities.
<img width="960" alt="User" src="https://user-images.githubusercontent.com/50138162/63350094-65a13180-c37a-11e9-80c6-a08352c3d768.png">

**Comment by dkasper-was-taken** [comment]
Yes, check for hero and userConfig as well. And we shouldn't show the menu toggle button in compact mode if we have none of the above info.

**Comment by tbiethman** [comment]
Regarding #2, the user information rendered in the popup may include more information than just the user name. I think if we have data from userConfig, we should always render the popup, as we'll likely have to render Logout anyway.

**Comment by neilpfeiffer** [comment]
Re-iterating:

> 1. In the following scenario do we check for the presence of "hero", since it is the only content in the Utilities?

Yes, shows button + utils menu if hero is provided. (Won't be common but yes).

> 2. A similar scenario here as well, when "userConfig" is the only item in the utilities. Also, the same user info is also shown in the dropdown button as well.

Yes, shows button + utils menu for userConfig, if any user info is provided. 

> 3. In the following scenario in mobile version, Do we need to handle an empty drawer?

If empty drawer, hides/removes the icon/button and never can show the drawer.
