### ISSUE TITLE
[terra-date-time-picker] onBlur prop given old date when DST modal closes

### ISSUE THREAD

**Issue by prmeznar** [cerner/terra-framework#856]
# Bug Report

## Description
When using the terra-date-time-picker, we are seeing some unexpected behavior around updating when the user enters an ambiguous hour. [This video](https://cernerprod.sharepoint.com/:v:/s/OrdersandPlansDev/Projects/EXiLcCgMyS1IsQPu-KZ7nyQBJLgf8rSiMx6cUC09nRCBlg?e=sS57gY) focuses on that behavior.

You can see on the initial selection of CST (-6:00), the -5:00 of CDT is still provided to our onBlur method and logged in the console. Our component then immediately calls our service to update the detail to this time. Once the update finishes, the detail has a value in CDT. When we click into and blur on the component again, we again pick CST, but CDT is provided to onBlur, meaning it looks like no change has occurred to the value and update is not called. (Note: Both of these times the user is incorrectly lead to believe the value is in CST, as the time zone button appears with CST displayed).

On our final "focus and blur" we see that update is called, because this time the onBlur function is correctly provided the CST (-6:00) value, so it observes a change and calls our services.

## Steps to Reproduce
1. Enter an ambiguous hour
2. Pick CST (while the current timezone is CDT)
3. Observe via logging or a breakpoint what value is passed to the onBlur prop

## Additional Context / Screenshots
--

## Expected Behavior
Value passed to the onBlur prop reflects the choice made in the DST modal

## Possible Solution
Looks like the issue is related to storing the dateTime in state when a modal button is clicked, and reading from state to pass to the consumers provided onBlur. This was evidenced by this change fixing the behavior:
![image](https://user-images.githubusercontent.com/47360296/63599093-76be8e00-c586-11e9-91c4-46d7f53b5cae.png)

By nesting the handleBlur call in a setState callback, we guarantee that all changes to state are propagated before calling handleBlur (which calls the consumers onBlur later). Rather than wrapping the handleBlur events in the two click handlers for the DST modal buttons, this could wrap where we read the state in handleBlur for a better guarantee of covering all workflows, but this approach could be seen as "smelly" and was really just used as a proof of concept.

What may be a better solution to this issue is no longer storing the dateTime in state, but passing it directly into the handleBlur event, so we don't have to worry about async state propagation.

## Environment

* Component Name and Version: terra-date-time-picker 4.10.0
* Browser Name and Version: Chrome, uh, recent

## @ Mentions
@benbcai

**Comment by nramamurth** [comment]
@prmeznar 

Um, this could be because of how I addressed [Ben's comment](https://github.com/cerner/terra-framework/pull/784#discussion_r309810982) in a PR earlier. I have now tried to fix it (_correctly?_) and here it is: https://github.com/cerner/terra-framework/commit/4fbb5e8621685a490a7614683c49e1d219b81e18 I have also built a snapshot if you would like to test it out using - 

```
"terra-date-time-picker": "https://github.cerner.com/terra/terra-snapshots/blob/master/terra-framework/ambiguous-hour-test/terra-date-time-picker.tgz?raw=true",
```
---
However, I am surprised that you see a Time Clarification dialog for the second time when you click into and blur the component again by clicking outside the date time picker component. I could be interpreting the logic or the video wrong but I think that the dialog does not (should not) show up when the old time is ambiguous according to the logic below. At this point, the time clarification dialog can be relaunched _only_ by clicking on the offset button.

https://github.com/cerner/terra-framework/blob/4a41737325ea81656c60520c26d37d6f512556f0/packages/terra-date-time-picker/src/DateTimePicker.jsx#L298

@benbcai Am I missing something?

**Comment by nramamurth** [comment]
@prmeznar 

I'd suggest logging a new issue regarding offset button highlight, I think it is not related to the original issue here - that would help separate out the investigation imo. 

@benbcai 

Do you see any concern with the [proposed changes](https://github.com/cerner/terra-framework/issues/856#issuecomment-524735600)?

**Comment by benbcai** [comment]
@nramamurth Your proposed changes makes sense and I could see where the mix up was in the initial change.

@prmeznar Was your app pulling in a version of terra-button prior to 3.20.0?

**Comment by prmeznar** [comment]
@benbcai It was pulling in 3.7.1 or I think. I saw the changelog for terra-button 3.20 mention fixing some programmatic focus bug, tried that out and verified it works in 3.20 but not 3.19
