### ISSUE TITLE
Responsive Tabs test appears to be inconsistent

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-framework#868]
# Bug Report

## Description
We're seeing the responsive tabs test fail periodically on travis CI. Need to investigate and see if theres something we can do to make this test more predictable. 

## Steps to Reproduce

1. Run travis CI build on terra-framework
2. Test for responsive tabs may fail with a slight visual mismatch diff

## Expected Behavior
Tests run predictably 

## Possible Solution
My need to see if we need to add a wait for some of the resize observers to complete before we take a screenshot?

## Environment

* Component Name and Version: terra-tabs

**Comment by avinashg1994** [comment]
The mentioned issue was only reproducible on Travis CI and it was not reproducible locally.
I tried the following approaches to resolve the same:

1. Added a delay of 100ms, 500ms and 1000ms, but the inconsistent behaviour still persisted. Although by adding a wait time of 1000ms, the number of failures were reduced but still frequent.
2. Reverted the code changes from PR #822 (suspecting that these changes were behind the failures) but the behaviour before and after the changes were the same.
3. Majority of the times, the failures occurred due to "Extended Tabs" for the various view ports. So, I tried to enclose the Extended Tabs describe block in a separate Viewport describe block. But this too did not resolve the problem.
4. Finally, i tried the following combination where I added a "wait time of 1000ms for the Default Tabs describe block" and "Browser.refresh() for the Extended Tabs describe block". Although it did not completely resolve the issue, it did significantly reduce the number of failure, i.e. **Among 12 Trials the wdios failed only 1 time**.
