### ISSUE TITLE
[terra-disclosure-manager] locale not respected if no `preferredType` passed in

### ISSUE THREAD

**Issue by dp21g** [cerner/terra-framework#909]
We used the code below and all of our i18n were not respected from the parent context. Even though all the functionality of the modal worked fine. Once we added `preferredType` as `modal` and changed the locale in terra-dev-site the modal displayed the locale translations. Is it required to pass this in when the 

```js
//Calendar.jsx
const Calendar = ({ is12HourTime, selectedDateTime, setSelectedDateTime }) => (
  <ModalManager>
<CalendarIcon is12HourTime={is12HourTime} selectedDateTime={selectedDateTime} setSelectedDateTime={setSelectedDateTime} />
</ModalManager>
);
```

```js
//CalendarIcon.jsx
        disclosureManager.disclose({
          preferredType: 'modal',
          dimensions: {
            height: '240',
            width: '480',
          },
          content: {
            key: 'calendar-modal-component-instance',
            component: <ModalComponent is12HourTime={is12HourTime} selectedDateTime={selectedDateTime} setSelectedDateTime={setSelectedDateTime} />,
          },
        });
```
Is this expected behaviour?
What would it default to if none are passed in?
What are the supported `preferredType` accepted in the API for disclose?

**Comment by lokesh-0813** [comment]
@dp21g  Could you provide the link to your repo or give us 'Steps to Reproduce' ?

**Comment by dp21g** [comment]
https://github.cerner.com/stella/stella-timeline

this is the fix I've got a PR for so once it goes in you may not be able to replicate within our codebase so make sure you revert to a commit before this PR.
https://github.cerner.com/stella/stella-timeline/pull/247

Once you have installed and ran npm start. Navigate to
http://localhost:8080/components/stella-timeline/timeline/timeline/timeline

When clicking on the calendar icon, it shows text which does not change based on locale selected. see below:


![locale-cal-modal-not-working](https://user-images.githubusercontent.com/6085036/66119416-82af5e00-e5d0-11e9-803c-163151afd3cc.gif)

**Comment by lokesh-0813** [comment]
@tbiethman

**Comment by tbiethman** [comment]
So here's a rough representation of the component hierarchy in dev site:
```
Dev Site -> Modal Manager A -> Component Page -> Modal Manager B -> Stella Timeline Example
```

There are two things contributing to the problem you're seeing.

First, when you change the locale within the Component Page (like you're doing in your gif), you're changing the locale for everything _below_ the Component Page (so ModalManager B and the Stella Timeline). Dev Site and Modal Manager A still have their previous locale that is set globally by dev site.

```
Dev Site -> Modal Manager A -> Component Page -> Modal Manager B -> Stella Timeline Example
En --------------------------------------------> Fr------------------------------------------>
```

Second, the Modal Managers in the application talk to each other. When your Stella Timeline Example makes its disclosure request, Modal Manager B gets the request first. It's line of thinking is "Okay, someone wants to disclose something. Let's check their preferredType to see if I support it. Hmm, it's empty. I know I support 'modal', but I'm not sure what to do with nothing. Well, do I have a DisclosureManager above me to delegate the request to? Ah, yeah Modal Manager A is there. I'm going to forward the request to Modal Manager A."  

Modal Manager A then has much of the same experience, up until it checks whether or not it has some to delegate the request to. It _does not_, so it throws its hands up and just presents the modal, lest the request go unhandled altogether.

However, since we determined that Modal Manager A is above the Component Page and thus uses the Dev Site's global locale, the content that gets presented from Modal Manager A uses the global locale. If you change the locale within the global dev site settings, you should see that locale reflected by the modal content.

When you provide a preferredType of 'modal' to your request, Modal Manager B handles the request because it understands the request type and doesn't delegate to Modal Manager A. And since Modal Manager B is within the context of the Component Page, the Component Page's locale is used.

So to answer your questions:
> Is this expected behaviour?

Yes, based on how you have it implemented. I'd recommend changing your implementation to specify the preferredType to change the behavior.

> What would it default to if none are passed in?

It would default to nothing. This will result in the highest DisclosureManager (ModalManager or otherwise) in the component hierarchy handling your disclosure request.

> What are the supported preferredType accepted in the API for disclose?
The ModalManager responds to a preferredType of 'modal'. The SlidePanelManager responds to a preferredType of 'panel'.

And as I side note, I see that you're implementing a ModalManager around an individual button. Ideally, you would render your ModalManager at a higher level (like Dev Site does) so that multiple components in your application can all use the same one. That way, you have better control of where and how modals are being presented application-wide, and your individual components don't have to worry about providing one.
